"""Traducciones ES → EN del historial de versiones (CHANGELOG de model.py).

Van aparte del diccionario de la interfaz: son notas largas que crecen con cada
versión. Toda entrada nueva del CHANGELOG necesita la suya aquí (lo exige
tests/test_i18n.py).
"""

EN_CHANGELOG: dict[str, str] = {
    # ── v1.3.0 ──
    "Idioma: las listas del panel derecho ya se traducen. La lista de utilidades mostraba el código interno de la capa («AGUA», «DRENAJE»…) aunque la app estuviera en inglés; ahora muestra el tipo en el idioma elegido («Agua»/«Water», «Drenaje»/«Storm Drain»…) y cambia al instante con el idioma. También se traducen la orientación de los leaders, «(sin familia)», los mensajes del panel «Mover con precisión» y la lista de bancoductos.":
        "Language: the right panel lists are now translated. The utility list showed the internal layer code («AGUA», «DRENAJE»…) even with the app in English; it now shows the type in the chosen language («Agua»/«Water», «Drenaje»/«Storm Drain»…) and switches instantly with the language. The leader orientation, «(no family)», the «Precise move» panel messages and the duct bank list are translated too.",
    "Accesorios sólidos con Property Set real: cada codo, Tee, Wye y cruz que crea el plugin trae el Property Set «PDFCAD_Accesorio», visible en Civil 3D en Propiedades → Extended Data, con Tipo_Accesorio, Angulo_Grados, Diametro_Pulg, Material y Cota_Eje_Pies. Sirve para filtrar, etiquetar y sacar cómputos. Antes esos datos solo iban como XDATA, que Civil 3D no muestra. Para dibujos importados antes, el comando PS_ACCESORIOS se los agrega.":
        "Solid fittings with a real Property Set: every elbow, Tee, Wye and cross the plugin creates carries the «PDFCAD_Accesorio» Property Set, visible in Civil 3D under Properties → Extended Data, with Tipo_Accesorio, Angulo_Grados, Diametro_Pulg, Material and Cota_Eje_Pies. Useful for filtering, labeling and quantity takeoffs. Before, this data was only stored as XDATA, which Civil 3D does not show. For drawings imported earlier, the PS_ACCESORIOS command adds it.",
    "Manual de usuario rediseñado: ahora se lee por capítulos cortos, con índice a la izquierda, botones «Anterior / Siguiente» y letra más grande o más pequeña (A+ / A−, se recuerda). Explica todo paso a paso y en lenguaje sencillo, con consejos y avisos destacados, e incluye una leyenda con los símbolos reales del lienzo y una tabla de cuándo sale cada alerta roja y qué hará Civil 3D. Respeta el modo claro/oscuro y está en español e inglés.":
        "Redesigned user manual: it now reads as short chapters, with an index on the left, «Previous / Next» buttons and larger or smaller text (A+ / A−, remembered). It explains everything step by step in plain language, with highlighted tips and warnings, and includes a legend with the real canvas symbols and a table of when each red alert appears and what Civil 3D will do. It follows light/dark mode and is available in Spanish and English.",
    "Corregido: al editar cualquier campo de una utilidad sin tamaño de catálogo (por ejemplo, el nombre), su diámetro quedaba en 0 y cambiaban las alertas del lienzo (un aviso rojo podía volverse ✓). Ahora se conserva el diámetro. Además, los mensajes de alertas y cruces nombran cada utilidad como «Agua - nombre de la red» (o solo «Agua» si no tiene nombre).":
        "Fixed: when editing any field of a utility without a catalog size (for example, the name), its diameter became 0 and the canvas alerts changed (a red warning could turn into ✓). The diameter is now kept. Also, alert and crossing messages name each utility as «Water - network name» (or just «Water» if it has no name).",
    "Conexión vertical aprobada en un quiebre con poco desnivel: cuando una utilidad pasa con un quiebre y la otra termina ahí, pero el desnivel no alcanza para bajar con dos codos de 90° (3.14 diámetros + 0.05 ft), aparece el triángulo rojo avisándolo. En Civil 3D ya no se deja sin conectar: se pone una Wye con el ramal inclinado y la tubería que termina se modifica para llegar a ella con pendiente (sin tubo auxiliar, codos ni vertical).":
        "Approved vertical connection at a bend with little elevation difference: when one utility passes with a bend and the other ends there, but the difference is not enough to drop with two 90° elbows (3.14 diameters + 0.05 ft), the red triangle warns about it. In Civil 3D it is no longer left unconnected: a Wye with a sloped branch is placed and the ending pipe is modified to reach it with a slope (no auxiliary pipe, elbows or vertical).",
    "Codos muy juntos en redes a presión: si entre dos codos queda un tramo más corto que 3 diámetros (mínimo 1 ft), aparece el triángulo rojo avisando que es muy corto y que en Civil 3D se reemplazará por un solo codo. El plugin ya no dibuja los dos codos montados uno sobre otro: une los dos quiebres en uno solo, en la intersección de los tramos vecinos (mismo giro total) y a la cota promedio.":
        "Elbows too close together in pressure networks: if the segment between two elbows is shorter than 3 diameters (minimum 1 ft), the red triangle warns that it is too short and that in Civil 3D it will be replaced by a single elbow. The plugin no longer draws the two elbows overlapping: it merges both bends into one, at the intersection of the neighboring segments (same total turn) and at the average elevation.",
    "Uniones de una misma utilidad a presión: donde dos tuberías se juntan a la misma cota (una termina sobre la otra o comparten vértice), el mensaje del lienzo ya no habla de «conflicto»: dice en pocas palabras qué hará Civil 3D (por ejemplo «una Wye sólida en la red «RED-GAS»»). Si tienen nombres de red distintos ya no sale la alerta roja de «redes distintas»: el plugin las mete en la misma red (la del primer nombre) y las une con el accesorio. La alerta roja queda solo para utilidades distintas (agua × drenaje).":
        "Joints within the same pressure utility: where two pipes meet at the same elevation (one ends on the other or they share a vertex), the canvas message no longer talks about a «conflict»: it says briefly what Civil 3D will do (for example «a solid Wye in network «RED-GAS»»). If they have different network names the red «different networks» alert no longer appears: the plugin puts them in the same network (the first name) and joins them with the fitting. The red alert remains only for different utilities (water × drainage).",
    "Idioma inglés completo: al cambiar de idioma, TODOS los textos cambian al instante — menús, barra de herramientas, paneles, pestañas, listas desplegables, tooltips, diálogos y sus botones, avisos del lienzo, mensajes del instalador de familias, validaciones del diseñador de bancoductos y avisos del reconocimiento. El manual y el historial de versiones también están en inglés. Antes quedaban cerca de 400 textos en español y algunos paneles no se actualizaban hasta reabrir la app.":
        "Complete English language: when changing the language, ALL texts switch instantly — menus, toolbar, panels, tabs, drop-down lists, tooltips, dialogs and their buttons, canvas warnings, family installer messages, duct bank designer validations and recognition notices. The user manual and the version history are also in English. Before, about 400 texts stayed in Spanish and some panels did not update until the app was reopened.",
    "Alerta de redes distintas: cuando dos utilidades de redes diferentes (por ejemplo agua y drenaje, o dos redes de agua con distinto nombre) se cruzan a la misma cota, el triángulo rojo reemplaza al círculo de conflicto y avisa que en Civil 3D no se conectarán y quedarán chocando.":
        "Different-networks alert: when two utilities from different networks (for example water and storm drain, or two water networks with different names) cross at the same elevation, the red triangle replaces the conflict circle and warns that in Civil 3D they will not be connected and will clash.",
    "Alerta de escalón de cota: si en un vértice de una misma tubería a presión el tramo que llega y el que sale tienen cotas distintas (por ejemplo, editadas en «Cotas por tramo»), aparece el triángulo rojo. Al hacer clic explica que Civil 3D no puede dibujar ese escalón y que unirá los dos tramos en la cota promedio. En drenaje y alcantarillado no aparece: ahí el escalón es una caída válida en el buzón.":
        "Elevation-step alert: if at a vertex of the same pressure pipe the incoming and outgoing segments have different elevations (for example, edited in «Elevations per segment»), the red triangle appears. Clicking it explains that Civil 3D cannot draw that step and will join both segments at the average elevation. It does not appear in storm drain and sanitary sewer: there the step is a valid drop in the manhole.",
    "Nueva advertencia en el lienzo: un triángulo rojo con «!» blanco marca los puntos donde se juntan 5 o más tuberías de una red a presión (agua, gas) a la misma cota. Civil 3D no puede unir tantas con un accesorio, así que ahí no se dibujaría ninguna pieza. Al pasar el mouse o hacer clic dice «Hay N tuberías en el mismo punto, no se dibujará ningún accesorio en Civil 3D, por favor corrija el dibujo». Reemplaza a los círculos de conflicto que antes se apilaban en ese punto. En drenaje y alcantarillado no aparece: ahí el buzón acepta los tubos que haga falta.":
        "New warning on the canvas: a red triangle with a white «!» marks the points where 5 or more pipes of a pressure network (water, gas) meet at the same elevation. Civil 3D cannot join that many with one fitting, so no part would be drawn there. Hovering or clicking says «There are N pipes at the same point; no fitting will be drawn in Civil 3D, please fix the drawing». It replaces the conflict circles that used to pile up at that point. It does not appear in storm drain and sanitary sewer: there the manhole accepts as many pipes as needed.",
    "Snap al dibujar utilidades: el marcador verde vuelve a verse siempre y ahora su FORMA dice a qué se engancha — círculo = extremo, cuadrado = vértice, triángulo = punto del tramo. La barra de estado lo confirma con un texto («⊙ Snap a vértice de «AGUA»»), útil cuando el marcador se pierde de vista con zoom bajo. Además, junto a un vértice el punto ya no se desliza unas décimas sobre el tramo: los vértices tienen prioridad, así las utilidades empalman exactamente donde se ve el marcador.":
        "Snap while drawing utilities: the green marker is always visible again and its SHAPE now tells what it snaps to — circle = end, square = vertex, triangle = point on the segment. The status bar confirms it with a text («⊙ Snap to vertex of «AGUA»»), useful when the marker gets lost at low zoom. Also, next to a vertex the point no longer slides a few tenths along the segment: vertices take priority, so utilities join exactly where the marker is shown.",
    "Nuevo lienzo en blanco (Archivo → «Nuevo lienzo…», Ctrl+N): ya no hace falta un PDF para empezar un proyecto. Se elige el tamaño de hoja (A0–A4, Carta, Oficio, Tabloide, ANSI A–E, ARCH C–E o medidas a mano en mm/pulgadas), la orientación y la escala del plano (1\"=10', 20', 30', 40', 50', 60', 100', 200' o personalizada). El diálogo muestra cuánto terreno real abarca la hoja con la escala elegida. Dibujar, guardar el proyecto y exportar a DXF funcionan igual que sobre un PDF.":
        "New blank canvas (File → «New canvas…», Ctrl+N): a PDF is no longer needed to start a project. You choose the sheet size (A0–A4, Letter, Legal, Tabloid, ANSI A–E, ARCH C–E or custom measurements in mm/inches), the orientation and the plan scale (1\"=10', 20', 30', 40', 50', 60', 100', 200' or custom). The dialog shows how much real ground the sheet covers at the chosen scale. Drawing, saving the project and exporting to DXF work the same as over a PDF.",
    "Bancoductos en Civil 3D 2027 (inglés): los conductos internos ahora se dibujan como cilindros 3D con el diámetro EXACTO que definiste (Ø1\", Ø2\", Ø3\", Ø4\", etc.). Antes, el catálogo de C3D rechazaba diámetros no estándar (por ejemplo Ø1\") y sumaba el espesor de pared, haciendo que los conductos se solaparan y sobresalieran de la envolvente.":
        "Duct banks in Civil 3D 2027 (English): the internal conduits are now drawn as 3D cylinders with the EXACT diameter you defined (Ø1\", Ø2\", Ø3\", Ø4\", etc.). Before, the C3D catalog rejected non-standard diameters (for example Ø1\") and added the wall thickness, making the conduits overlap and stick out of the envelope.",
    "Validación en vivo del radio de curva: al seleccionar un elemento curvo, el campo «Radio (Pies)» muestra en rojo el máximo permitido por la geometría (tramos rectos adyacentes). El campo no deja escribir un valor mayor, y si el valor guardado excede el nuevo máximo, se ajusta automáticamente con un aviso explicando por qué.":
        "Live validation of the curve radius: when selecting a curved element, the «Radius (ft)» field shows in red the maximum allowed by the geometry (adjacent straight segments). The field does not accept a larger value, and if the saved value exceeds the new maximum, it is adjusted automatically with a warning explaining why.",
    "Uniones tipo Y (Wye) reales: al importar redes de presión con junturas de 3 tuberías en ~120°, el plugin ahora carga automáticamente las familias Wye (30/45/60/75/90°) del catálogo Imperial_AWWA_Steel a la PressurePartList activa y coloca la pieza real correspondiente. Funciona en Civil 3D 2025/2026/2027 en español o inglés (detecta la carpeta de idioma instalada).":
        "Real Wye junctions: when importing pressure networks with 3-pipe junctions at ~120°, the plugin now automatically loads the Wye families (30/45/60/75/90°) from the Imperial_AWWA_Steel catalog into the active PressurePartList and places the corresponding real part. It works in Civil 3D 2025/2026/2027 in Spanish or English (it detects the installed language folder).",
    "Detección automática de cruces físicos de utilidades en el lienzo: cada punto donde un tramo de una utilidad CRUZA (no comparte extremo) otro tramo aparece con un círculo amarillo con «!» rojo. Sirve para revisar profundidades cuando dos utilidades se pasan por encima/debajo sin ser una juntura. Tooltip indica qué capas se cruzan; contador en la barra de estado. Se puede ocultar con el toggle «Mostrar cruces/conflictos» del menú Ver.":
        "Automatic detection of physical utility crossings on the canvas: every point where a segment of one utility CROSSES (does not share an end with) another segment appears with a yellow circle with a red «!». It helps review depths when two utilities pass over/under each other without being a junction. The tooltip shows which layers cross; counter in the status bar. It can be hidden with the «Show crossings/conflicts» toggle in the View menu.",
    "Snap suave al dibujar utilidades: cuando el cursor se acerca a una utilidad EXISTENTE del mismo tipo (extremo, vértice intermedio o cualquier punto del tramo), aparece un círculo verde marcando dónde se pegaría el click. Si el primer click se pega al EXTREMO de otra utilidad del mismo tipo, la app pregunta si quieres «unirla como parte de esa utilidad» o «crear una utilidad nueva que la toca» (juntura automática al importar).":
        "Soft snap while drawing utilities: when the cursor gets close to an EXISTING utility of the same type (end, intermediate vertex or any point of the segment), a green circle appears marking where the click would snap. If the first click snaps to the END of another utility of the same type, the app asks whether you want to «join it as part of that utility» or «create a new utility that touches it» (automatic junction on import).",
    "Componer hoja de trabajo: al abrir un PDF vectorial se elige la hoja, se marca el área del plano que interesa y se «toma» a una hoja compuesta, como un XREF. Se pueden tomar piezas de varias hojas y de otros PDF, girarlas, corregir su escala y acomodarlas con el imán (los extremos de las líneas se pegan a los de la pieza vecina). Cada pieza conserva sus vectores, capas, textos y medidas; la hoja compuesta es un PDF real de una sola página con todas las capas, y el reconocimiento corre una sola vez sobre ella, así las líneas que cruzan de una hoja a otra salen como una sola ruta.":
        "Compose work sheet: when opening a vector PDF you choose the sheet, mark the area of interest of the plan and «take» it into a composite sheet, like an XREF. You can take pieces from several sheets and from other PDFs, rotate them, correct their scale and arrange them with the magnet (line ends snap to those of the neighboring piece). Each piece keeps its vectors, layers, texts and measurements; the composite sheet is a real single-page PDF with all the layers, and recognition runs only once on it, so lines crossing from one sheet to another come out as a single route.",
    "En el compositor, los extremos de línea en el borde de cada pieza se marcan con un punto y los «Puentes» unen cada extremo con el que tiene enfrente en la pieza vecina (misma capa, hueco máximo configurable) con un trazo vectorial en esa misma capa: así se puede recortar cada hoja por dentro de su match line, sin la línea divisoria, y el reconocimiento sigue la utilidad de una pieza a la otra como una sola ruta. El imán también alinea piezas separadas por un hueco (deja los extremos en línea sin cerrarlo).":
        "In the composer, line ends on the edge of each piece are marked with a dot and «Bridges» join each end with the one facing it on the neighboring piece (same layer, configurable maximum gap) with a vector stroke on that same layer: this way each sheet can be cropped inside its match line, without the dividing line, and recognition follows the utility from one piece to the other as a single route. The magnet also aligns pieces separated by a gap (it keeps the ends in line without closing it).",
    "«Imán a líneas» en el área a tomar: al arrastrar el rectángulo (lados, esquinas o el área entera) sus lados saltan a las líneas generales de la hoja — match lines (también a guiones), marcos y bordes largos — y la guía usada se resalta en celeste. Entre varias a tiro gana la más larga.":
        "«Snap to lines» in the area to take: when dragging the rectangle (sides, corners or the whole area) its sides jump to the sheet's general lines — match lines (also dashed), frames and long edges — and the guide used is highlighted in light blue. Among several within reach, the longest one wins.",
    "Precisión del reconocimiento en quiebres suaves y bóvedas: la simplificación de quiebres blandos baja de 1.5 a 0.5 pt, así la centerline ya no se aparta de los guiones hasta 1.5 pt en las transiciones (DU06 hoja 14: desvío p90 de 0.83 a 0.28 pt).":
        "Recognition accuracy at soft breaks and vaults: soft-break simplification goes down from 1.5 to 0.5 pt, so the centerline no longer drifts up to 1.5 pt away from the dashes at transitions (DU06 sheet 14: p90 deviation from 0.83 to 0.28 pt).",
    "«Sin línea de borde» (activo por defecto): al tomar un área, cada lado se lleva al CENTRO de la línea larga que corra pegada a él (match line, marco de la vista), sea de la capa que sea y aunque vaya a guiones gruesos, y su tinta se tapa con una franja blanca. Así no se pierde ningún vector (los de debajo de la línea siguen ahí para el reconocimiento) y dos hojas contiguas se unen borde con borde sin hueco ni línea divisoria. Las grillas (series de paralelas) no cuentan.":
        "«No border line» (on by default): when taking an area, each side is moved to the CENTER of the long line running next to it (match line, view frame), whatever its layer and even if it is thick-dashed, and its ink is covered with a white strip. This way no vector is lost (the ones under the line are still there for recognition) and two adjacent sheets join edge to edge with no gap and no dividing line. Grids (series of parallel lines) do not count.",
    "Codos reconocidos como esquina + radio: cuando los vértices de un codo caen sobre un círculo y las rectas que llegan y salen son tangentes a él, la ristra se sustituye por la esquina (intersección de tangentes) y la CAJA de ese vértice pasa a ser una esquina curva «CV» con `radius_ft` — el mismo modelo del dibujo manual, con el que el plugin genera la tubería curva tangente en Civil 3D. La vista previa dibuja el arco sobre la curva del PDF, las tangentes punteadas y la esquina. Solo cuenta como arco lo que el PDF dibuja como trazo curvo (Béziers / trazo continuo); una cadena de guiones rectos con quiebres se queda como esquinas, y las curvas suaves (giro < 8°) o sin recta tangente quedan como polilínea: no se inventa nada.":
        "Bends recognized as corner + radius: when the vertices of a bend fall on a circle and the incoming and outgoing lines are tangent to it, the string of vertices is replaced by the corner (intersection of tangents) and the BOX at that vertex becomes a «CV» curved corner with `radius_ft` — the same model as manual drawing, which the plugin uses to generate the tangent curved pipe in Civil 3D. The preview draws the arc over the PDF curve, the dotted tangents and the corner. Only what the PDF draws as a curved stroke (Béziers / continuous stroke) counts as an arc; a chain of straight dashes with breaks stays as corners, and soft curves (turn < 8°) or ones without a tangent line stay as a polyline: nothing is made up.",
    "Bóvedas abandonadas: el contorno que va dibujado en la propia capa de estado «-A» (lazo cerrado de 4 corridas) se reconoce como bóveda con contorno, medidas y giro, igual que las activas; la vista previa la marca «(AB)» y la CAJA que la línea abandonada deja en su borde recibe esa geometría al importar.":
        "Abandoned vaults: the outline drawn on the «-A» status layer itself (closed loop of 4 runs) is recognized as a vault with outline, measurements and rotation, just like active ones; the preview marks it «(AB)» and the BOX that the abandoned line leaves at its edge receives that geometry on import.",
    "Líneas abandonadas con «//»: además de la barra simple, se reconoce el doble slash como marcador — dibujado como dos barras sueltas o como un solo trazo en zigzag — y también barras más largas (hasta 18 pt) siempre que crucen la línea por su interior o la línea siga a ambos lados; el tick «|» que remata un tramo no se toca. Un trazo en zigzag con giros > 60° ya no se confunde con un codo.":
        "Abandoned lines with «//»: besides the single bar, the double slash is recognized as a marker — drawn as two loose bars or as a single zigzag stroke — as well as longer bars (up to 18 pt) as long as they cross the line through its interior or the line continues on both sides; the «|» tick that ends a segment is left untouched. A zigzag stroke with turns > 60° is no longer mistaken for a bend.",
    "Una línea es abandonada solo si se cumplen las dos cosas: está en la capa de estado «-A» Y sigue el patrón de marcadores «/» en toda su longitud (el paso entre marcadores se aprende del propio plano con ≥3 marcadores seguidos a la misma distancia; cada línea se juzga sola y los ramales más cortos que el paso heredan el veredicto de su capa). Dos barras sueltas no hacen una abandonada, ni el nombre de la capa por sí solo. La vista previa avisa de las líneas de capa «-A» sin patrón (se importan activas) y del patrón «/» hallado en una capa activa (manda la capa; revisar).":
        "A line is abandoned only if both conditions are met: it is on the «-A» status layer AND it follows the «/» marker pattern along its whole length (the pitch between markers is learned from the plan itself with ≥3 consecutive markers at the same distance; each line is judged on its own and branches shorter than the pitch inherit their layer's verdict). Two loose bars do not make an abandoned line, nor does the layer name by itself. The preview warns about «-A» layer lines without the pattern (they are imported as active) and about the «/» pattern found on an active layer (the layer wins; review).",
    "Vista previa: las bóvedas huérfanas (cajas propuestas de otro paquete, cajas de paso, postes) van como marca discreta sin contorno ni medida, y un símbolo con lado menor de 2 ft no se mide como bóveda.":
        "Preview: orphan vaults (proposed boxes from another package, pull boxes, poles) are shown as a discreet mark without outline or measurement, and a symbol with a short side under 2 ft is not measured as a vault.",
    "Bóvedas eléctricas con su geometría real: el reconocimiento toma del PDF el contorno del símbolo (rectángulo con su giro, o círculo) y sus medidas en pies; la vista previa las dibuja con el color de la utilidad (el mismo de las cajas del editor) y «ancho × largo ft», y al importar la CAJA correspondiente guarda forma, medidas y contorno, que se dibuja a escala en el lienzo (la medida aparece al seleccionarla). El DXF exporta SHAPE, WIDTH_FT, LENGTH_FT y ROT_DEG en la estructura. Nada se inventa: las bóvedas sin línea que las atraviese no crean buzón.":
        "Electrical vaults with their real geometry: recognition takes from the PDF the outline of the symbol (rectangle with its rotation, or circle) and its measurements in feet; the preview draws them with the utility color (the same as the editor boxes) and «width × length ft», and on import the corresponding BOX stores shape, measurements and outline, which is drawn to scale on the canvas (the measurement appears when you select it). The DXF exports SHAPE, WIDTH_FT, LENGTH_FT and ROT_DEG on the structure. Nothing is made up: vaults without a line crossing them do not create a manhole.",
    "Líneas eléctricas muy cercanas: una línea que terminaba a ≤3 pt de otra paralela se enganchaba como ramal (T) y quedaban interconectadas. La convergencia rasante ahora exige que la línea realmente se acerque a la otra. Auditoría con paralelas hasta 2 pt (0.56 ft a 1\"=20'): se mantienen separadas.":
        "Very close electrical lines: a line ending ≤3 pt from a parallel one was hooked as a branch (T) and they ended up interconnected. The grazing convergence now requires the line to actually approach the other one. Audit with parallel lines down to 2 pt (0.56 ft at 1\"=20'): they stay separate.",
    "Pantallas pequeñas: en el compositor cada panel se puede plegar a una tira (botón ‹ en su cabecera) para dar sitio a los demás, el ancho inicial de los paneles es proporcional a la ventana y se recuerda, y el texto de ayuda se oculta en ventanas estrechas. «Capas de la hoja» y «Vista previa del reconocimiento» abren maximizadas y su panel derecho va en un divisor arrastrable (ancho según la pantalla, nunca más del 32 %). El minimapa es más pequeño (150 × 110).":
        "Small screens: in the composer each panel can be collapsed into a strip (‹ button on its header) to give room to the others, the initial panel width is proportional to the window and remembered, and the help text is hidden in narrow windows. «Sheet layers» and «Recognition preview» open maximized and their right panel goes in a draggable splitter (width according to the screen, never more than 32 %). The minimap is smaller (150 × 110).",
    "Codos reconocidos, auditoría al milímetro: la esquina y las tangentes salen de las RECTAS de los guiones del plano (no del empalme corto entre el último guión y el trazo curvo, ni del salto sobre una letra «e»), y el círculo es el tangente a esas dos rectas que pasa por el trazo curvo del PDF. En el DU06 (hoja 4) un codo quedaba con la esquina 3.7 pt fuera y la tangente torcida 4.75°; ahora las cuatro tangentes caen sobre los guiones a menos de 0.5 pt y el arco sobre la tinta a menos de 1 pt. Nada se inventa: si el arco no es tangente a sus rectas se queda como polilínea. Se cubren huecos/letra antes del arco, arcos a guiones, giros de 30° a 120° y curvas compuestas (dos radios no se funden en uno).":
        "Recognized bends, millimeter audit: the corner and tangents come from the LINES of the plan's dashes (not from the short joint between the last dash and the curved stroke, nor from the jump over an «e» letter), and the circle is the one tangent to those two lines that passes through the PDF's curved stroke. In DU06 (sheet 4) one bend had its corner 3.7 pt off and its tangent 4.75° skewed; now the four tangents fall on the dashes within 0.5 pt and the arc on the ink within 1 pt. Nothing is made up: if the arc is not tangent to its lines it stays as a polyline. Gaps/letters before the arc, dashed arcs, turns from 30° to 120° and compound curves (two radii are not merged into one) are covered.",
    "El editor dibuja el arco REAL de cada esquina curva (tangente a los dos tramos con el radio en pies, mismos puntos de tangencia que generará el plugin) en vez de un símbolo de codo a escala fija que no caía sobre la curva del plano; los puntos de tangencia se marcan y, si el radio no entra en los tramos (el plugin lo recorta), el arco va a trazos.":
        "The editor draws the REAL arc of each curved corner (tangent to both segments with the radius in feet, same tangent points the plugin will generate) instead of a fixed-scale bend symbol that did not fall on the plan's curve; the tangent points are marked and, if the radius does not fit in the segments (the plugin trims it), the arc is dashed.",
    "«Capas de la hoja»: las casillas del panel Utilidades ya no solo filtran la lista — desmarcar una utilidad (Agua, Gas…) apaga todas sus capas en la hoja (y en el reconocimiento) y las quita de la lista; al volver a marcarla cada capa recupera el estado que tenía. «Todas» enciende/apaga el conjunto. El buscador sigue siendo solo un filtro.":
        "«Sheet layers»: the checkboxes in the Utilities panel no longer just filter the list — unchecking a utility (Water, Gas…) turns off all its layers on the sheet (and in recognition) and removes them from the list; checking it again restores each layer to its previous state. «All» turns the whole set on/off. The search box is still only a filter.",
    "Minimapa en «Capas de la hoja» (esquina inferior izquierda): esquema de cómo está organizada la hoja de trabajo — una caja por hoja tomada, con su número (y su PDF si hay varios) en su posición relativa — y el recuadro de lo que se ve en pantalla. Clic o arrastre en el mapa centra la vista ahí.":
        "Minimap in «Sheet layers» (bottom left corner): a diagram of how the work sheet is organized — one box per taken sheet, with its number (and its PDF if there are several) in its relative position — and the frame of what is visible on screen. Clicking or dragging on the map centers the view there.",
    "Unión recta: tras el imán, un ajuste fino por mínimos cuadrados con todas las parejas de extremos afina la posición a centésimas de punto (las líneas inclinadas fijan también la normal de la costura), y cada puente prolonga la línea por su propia recta hasta el borde de su pieza en vez de ir en diagonal de extremo a extremo (sin quiebre angular).":
        "Straight join: after the magnet, a least-squares fine adjustment with all the pairs of ends refines the position to hundredths of a point (inclined lines also fix the seam's normal), and each bridge extends the line along its own direction up to the edge of its piece instead of going diagonally from end to end (no angular break).",
    "Costura milimétrica entre piezas: desaparece la línea finísima que quedaba en la unión (antialiasing del borde: la franja blanca ahora sobresale 0.5 pt hacia afuera), los extremos y puentes se toman en el borde interior de la franja para que cada línea que cruza se complete encima de ella, y el imán une los bordes de las piezas exactamente (borde con borde) alineando de lado solo a lo largo de la costura.":
        "Millimeter seam between pieces: the very thin line left at the join disappears (edge antialiasing: the white strip now sticks out 0.5 pt outwards), ends and bridges are taken at the inner edge of the strip so each crossing line is completed on top of it, and the magnet joins the piece edges exactly (edge to edge), aligning sideways only along the seam.",
    "Calidad de imagen: en «Área a tomar» y en la hoja compuesta, al hacer zoom se re-renderiza nítida la parte visible (de TODAS las piezas a la vista, con tope de píxeles), en vez de una sola pieza «enfocada».":
        "Image quality: in «Area to take» and in the composite sheet, zooming re-renders the visible part sharply (of ALL the pieces in view, with a pixel cap), instead of a single «focused» piece.",
    "El compositor abre maximizado a la primera (antes hacían falta dos clics).":
        "The composer opens maximized the first time (before it took two clicks).",
    "Seleccionar una pieza en la hoja compuesta lleva el panel «Área a tomar» a su PDF y hoja con su área marcada: al ajustar el rectángulo la pieza se actualiza sola. «Nueva pieza» vuelve al modo normal.":
        "Selecting a piece in the composite sheet takes the «Area to take» panel to its PDF and sheet with its area marked: adjusting the rectangle updates the piece by itself. «New piece» returns to normal mode.",
    "Los extremos para el imán y los puentes solo salen de trazos de línea (≥3 pt, sin letras ni símbolos explotados ni rellenos); un extremo que muere cerca del borde alinea y hace puente pero no pega piezas (evita solapes). Botones de acción solo con icono (Agregar PDF, girar, quitar, ajustar).":
        "Ends for the magnet and bridges only come from line strokes (≥3 pt, no letters, exploded symbols or fills); an end that dies near the edge aligns and bridges but does not stick pieces together (avoids overlaps). Icon-only action buttons (Add PDF, rotate, remove, fit).",
    "«Organizar hojas» deja de ser un paso del asistente (sigue en el menú Ver). El botón «Cambiar de hoja…» del preview ahora es «Componer hoja…» y vuelve al compositor. Menú Ver → «Componer hoja de trabajo…» lo abre en cualquier momento.":
        "«Arrange sheets» is no longer a wizard step (it is still in the View menu). The preview's «Change sheet…» button is now «Compose sheet…» and returns to the composer. View menu → «Compose work sheet…» opens it at any time.",
    "El proyecto guarda la composición y los PDF de origen completos; al reabrir se puede volver al compositor con todo igual.":
        "The project saves the composition and the complete source PDFs; when reopening you can go back to the composer with everything as it was.",
    # ── v1.1.9 ──
    "Los tramos reconocidos de la misma capa se unen en rutas por buena continuación: en cada cruce se sigue de frente y el ramal empieza otra ruta. Si no hay trayectoria clara, no se une nada. No se mueven ni se inventan puntos, ni se cruzan capas distintas o activas con abandonadas. En la vista previa, «Unir tramos en rutas» (activada) lo deshace al momento.":
        "Recognized segments of the same layer are joined into routes by good continuation: at each crossing the route goes straight ahead and the branch starts another route. If there is no clear path, nothing is joined. No points are moved or made up, and different layers or active with abandoned are never crossed. In the preview, «Join segments into routes» (on) undoes it instantly.",
    # ── v1.1.8 ──
    "Las utilidades eléctricas abandonadas se dibujan del mismo color que la activa. Solo se distinguen por (AB) en la lista; ya no van a trazos ni con otro matiz.":
        "Abandoned electrical utilities are drawn in the same color as the active one. They are only distinguished by (AB) in the list; they are no longer dashed or in another shade.",
    # ── v1.1.7 ──
    "Un ramal de la misma capa eléctrica (guiones del linetype, aunque uno sea un poco más largo, más el codo) se une a la centerline: nace en la línea principal, quiebra en el codo y el otro extremo queda libre. Ya no se pinta violeta como leader. Un trazo continuo solo, sin contacto con esa red, sigue fuera.":
        "A branch of the same electrical layer (linetype dashes, even if one is a bit longer, plus the bend) joins the centerline: it starts on the main line, breaks at the bend and the other end stays free. It is no longer painted purple as a leader. A lone continuous stroke with no contact with that network stays out.",
    # ── v1.1.6 ──
    "El reconocimiento reconstruye cada capa OCG de líneas por separado: una capa eléctrica que no es la utilidad (p.ej. U-PROP-ESFV-ELEC-STRUCT) ya no se cose ni se imana con C-ELEC-UNGD-E. Las bóvedas solo cuentan si son un símbolo compacto con caja/círculo; un linetype disfrazado de estructura no atrae extremos. Los ramales de la misma capa que quedaban sin dibujar se cubren si son guiones del patrón.":
        "Recognition rebuilds each OCG line layer separately: an electrical layer that is not the utility (e.g. U-PROP-ESFV-ELEC-STRUCT) is no longer stitched or snapped to C-ELEC-UNGD-E. Vaults only count if they are a compact symbol with a box/circle; a linetype disguised as a structure does not attract ends. Same-layer branches that were left undrawn are covered if they are pattern dashes.",
    # ── v1.1.5 ──
    "Utilidades eléctricas ABANDONADAS: la capa de estado «-A» (C-ELEC-UNGD-A, linetype «──/── e ──») se reconoce igual que la activa pero se importa marcada como abandonada (AB), como la casilla «Abandonado» del dibujo manual (en el DXF sale con el linetype discontinuo). Las barras «/» del linetype se tratan como marcadores (no quedan «sin cubrir»); el contorno de bóveda que el plot dibuja en esa misma capa se detecta como bóveda (la línea para en su borde y el contorno no se dibuja); activas y abandonadas se reconstruyen por separado (son pipes distintas). En la vista previa van a trazos y la lista de capas las señala «(abandonada)».":
        "ABANDONED electrical utilities: the «-A» status layer (C-ELEC-UNGD-A, linetype «──/── e ──») is recognized like the active one but imported marked as abandoned (AB), like the «Abandoned» checkbox of manual drawing (in the DXF it comes out with the dashed linetype). The linetype's «/» bars are treated as markers (they are not left «uncovered»); the vault outline the plot draws on that same layer is detected as a vault (the line stops at its edge and the outline is not drawn); active and abandoned are rebuilt separately (they are different pipes). In the preview they are dashed and the layer list flags them «(abandoned)».",
    "Bóvedas: un trazo continuo (sin patrón) que solo nace en el borde y sale hacia afuera ya no se toma como continuación de la línea que llega por el lado opuesto (ambos paran en el borde); sí cuenta si el trazo entra y cruza la bóveda.":
        "Vaults: a continuous stroke (no pattern) that only starts at the edge and goes outwards is no longer taken as the continuation of the line arriving from the opposite side (both stop at the edge); it does count if the stroke enters and crosses the vault.",
    "Un ramal abandonado que nace sobre su propia línea junto a una bóveda activa ya no se «engancha» a esa bóveda con un tramo inventado: un extremo que muere sobre otra línea es una T con esa línea (nos basamos en las capas).":
        "An abandoned branch that starts on its own line next to an active vault no longer «hooks» onto that vault with a made-up segment: an end that dies on another line is a T with that line (we rely on the layers).",
    "Precisión de los puntos de quiebre: un extremo que muere sobre otra corrida es una T sobre ella (antes podía formar una esquina fuera de la línea con un tercer extremo cercano); los ticks «┤» de fin de tramo quedan como extremo–T–extremo y sus puntas nunca se unen a otra línea (ni a la que muere a 4 pt de ellas); una esquina nunca se traga más de media corrida; un cruce en X con hueco sigue siendo una sola línea; la línea que atraviesa una bóveda y sigue un trozo corto conserva borde, nodo, borde y su extremo; y las transiciones suaves se simplifican a 1.5 pt (las curvas siguen a 1 pt). Hoja 9 del DU06: 98.4 % → 100 %.":
        "Accuracy of break points: an end that dies on another run is a T on it (before it could form a corner off the line with a nearby third end); the «┤» end-of-segment ticks stay as end–T–end and their tips never join another line (not even the one that dies 4 pt from them); a corner never swallows more than half a run; an X crossing with a gap is still a single line; the line that crosses a vault and continues a short stretch keeps edge, node, edge and its end; and soft transitions are simplified to 1.5 pt (curves stay at 1 pt). DU06 sheet 9: 98.4 % → 100 %.",
    "Ya no se pide confirmar las capas eléctricas: las capas de líneas y bóvedas se asignan solas por su nombre y la vista previa del reconocimiento las muestra de forma informativa (cabecera con la utilidad y su color, «Capas usadas: Líneas / Bóvedas»). Si el plot usa otros nombres, «Ajustar capas…» permite indicarlas a mano y vuelve a reconocer; si no se encontró ninguna, la vista previa lo avisa y no deja importar.":
        "Confirming the electrical layers is no longer required: line and vault layers are assigned automatically by name and the recognition preview shows them for information (header with the utility and its color, «Layers used: Lines / Vaults»). If the plot uses other names, «Adjust layers…» lets you set them by hand and recognizes again; if none was found, the preview warns about it and does not allow importing.",
    "«Cambiar de hoja…» en la vista previa del reconocimiento: lista de hojas → capas de la hoja → vista previa de la hoja nueva ya reconocida, sin pasar por el editor.":
        "«Change sheet…» in the recognition preview: sheet list → sheet layers → preview of the new sheet already recognized, without going through the editor.",
    # ── v1.1.4 ──
    "Paso «Capas de la hoja» reorganizado: las capas se agrupan por utilidad (Agua, Alcantarillado, Drenaje, Gas, Eléctrico, Telefonía y Otras — las mismas del desplegable «Tipo de utilidad», cada una con su color) a partir del nombre de la capa; el panel «Utilidades» filtra la lista (o «Todas») y combina con el buscador.":
        "Reorganized «Sheet layers» step: layers are grouped by utility (Water, Sanitary sewer, Storm drain, Gas, Electrical, Telecom and Other — the same ones as the «Utility type» dropdown, each with its color) based on the layer name; the «Utilities» panel filters the list (or «All») and combines with the search box.",
    "Cambio de hoja sin salir del paso de capas (◀ Hoja N / M ▶): la vista previa y los conteos se actualizan y las capas marcadas se conservan. Después, al cambiar de hoja en el editor (◀ ▶ o nº de página) la nueva hoja se reconoce con las mismas capas y roles ya confirmados y se muestra la vista previa para importar.":
        "Change sheets without leaving the layers step (◀ Sheet N / M ▶): the preview and counts are updated and checked layers are kept. Afterwards, when changing sheets in the editor (◀ ▶ or page number) the new sheet is recognized with the same layers and roles already confirmed, and the preview is shown for importing.",
    # ── v1.1.3 ──
    "Reconocimiento eléctrico: centerlines más continuas y precisas (snap de extremos, colapso de trazos paralelos, cosido colineal por grafo y Douglas–Peucker). Menos cortes artificiales y menos dobles desfasados en el preview.":
        "Electrical recognition: more continuous and accurate centerlines (end snapping, collapse of parallel strokes, graph-based collinear stitching and Douglas–Peucker). Fewer artificial cuts and fewer offset duplicates in the preview.",
    # ── v1.1.2 ──
    "Tras elegir capas, se confirman roles OCG (líneas / bóvedas / ignorar) por si el plot usa otros nombres.":
        "After choosing layers, the OCG roles (lines / vaults / ignore) are confirmed in case the plot uses other names.",
    "El reconocimiento eléctrico vuelve a correr: preview con líneas listas (inicio, quiebres, fin) como dibujo manual y bóvedas VALT como puntos; Continuar las importa al editor (pipes ELECTRICO + cajas).":
        "Electrical recognition runs again: preview with finished lines (start, breaks, end) like manual drawing and VALT vaults as points; Continue imports them into the editor (ELECTRICO pipes + boxes).",
    # ── v1.1.1 ──
    "Vista previa de reconocimiento al abrir un PDF bien ploteado: eliges la hoja, se reconocen utilidades eléctricas subterráneas (capas C-ELEC-UNGD) y se muestran dibujadas como el trazo manual. Solo preview — aún no se importan al inventario.":
        "Recognition preview when opening a properly plotted PDF: you choose the sheet, underground electrical utilities (C-ELEC-UNGD layers) are recognized and shown drawn like the manual stroke. Preview only — they are not imported into the inventory yet.",
    "Reconocimiento eléctrico reconstruido desde cero (núcleo geométrico nuevo): aprende el patrón del linetype del propio plano (guiones, letras «e», huecos), reconstruye cada corrida de inicio a fin con sus quiebres, resuelve esquinas por intersección exacta, T, quiebres suaves, arcos discontinuos y bóvedas como vértices compartidos. Un extremo nunca se mueve fuera de su propia recta, así ninguna línea se inclina. Cobertura medida en el DU06: 97–100 % por hoja (antes 75–89 %).":
        "Electrical recognition rebuilt from scratch (new geometric core): it learns the linetype pattern from the plan itself (dashes, «e» letters, gaps), rebuilds each run from start to end with its breaks, resolves corners by exact intersection, Ts, soft breaks, discontinuous arcs and vaults as shared vertices. An end never moves off its own line, so no line gets tilted. Coverage measured on DU06: 97–100 % per sheet (before 75–89 %).",
    "La vista previa muestra control de calidad: porcentaje de cobertura, guiones que ninguna línea cubrió (naranja), trazos continuos fuera de patrón como leaders/flechas (violeta, no se importan) y bóvedas sin línea cercana.":
        "The preview shows quality control: coverage percentage, dashes no line covered (orange), off-pattern continuous strokes such as leaders/arrows (purple, not imported) and vaults with no nearby line.",
    "Al importar, los quiebres sin bóveda (esquinas suaves, arcos) quedan como cajas OCULTAS (Estructura nula en Civil 3D): solo las bóvedas reales salen como CAJA visible. Las pipes reconocidas guardan el tipo de cada vértice en el proyecto.":
        "On import, breaks without a vault (soft corners, arcs) stay as HIDDEN boxes (Null structure in Civil 3D): only real vaults come out as a visible BOX. Recognized pipes store the type of each vertex in the project.",
    "Las líneas reconocidas ya no superan el marco de la vista de planta: la geometría se recorta por los clips reales del PDF (marco de la vista, XCLIP de referencias) y un extremo creado por el recorte no forma esquinas ni se prolonga. Los codos «⌒» que conectan un conduit con el borde de la bóveda se reconocen como curvas (antes se descartaban como letras).":
        "Recognized lines no longer go beyond the plan view frame: the geometry is clipped by the real PDF clips (view frame, reference XCLIP) and an end created by the clipping does not form corners nor get extended. The «⌒» bends that connect a conduit with the vault edge are recognized as curves (before they were discarded as letters).",
    "Bóvedas, ajustes finos: la llegada al nodo interior es un solo tramo recto borde→nodo (sin quiebre intermedio); un stub corto colineal con una línea al otro lado de la bóveda cuenta como continuidad de esa línea; las curvas/continuas que salen de una bóveda nunca se cosen entre sí en sus puntas (conduits cortados por el límite de la vista); los trozos cortos que tocan una bóveda se conservan y se conectan al nodo de llegada más cercano.":
        "Vaults, fine adjustments: the arrival at the inner node is a single straight edge→node segment (no intermediate break); a short stub collinear with a line on the other side of the vault counts as that line's continuation; curves/continuous strokes leaving a vault are never stitched to each other at their tips (conduits cut by the view limit); short pieces touching a vault are kept and connected to the nearest arrival node.",
    "Reglas de bóveda según los apuntes (revisadas): toda línea llega al buzón por su propia recta y SIEMPRE deja un punto de quiebre donde choca con el borde (entrada y salida). Dentro del buzón no se inventa nada a partir del símbolo: si una línea de red lo atraviesa (o dos llegan colineales por lados opuestos), el nodo interior se calcula con las llegadas —sobre la línea que atraviesa, en la intersección si son dos— y las demás llegan a él siguiendo su eje con un quiebre corto. Si ninguna línea lo atraviesa (bóveda grande, stubs, curvas), cada una termina en el borde y ahí queda su caja: el usuario completa a mano. Dos conduits que convergen en ángulo rasante nacen en un vértice compartido sobre la línea principal; las corridas se parten donde los guiones se apartan >0.75 pt para que todo vértice quede sobre la línea de la capa.":
        "Vault rules according to the notes (reviewed): every line reaches the manhole along its own line and ALWAYS leaves a break point where it hits the edge (entry and exit). Nothing is made up inside the manhole from the symbol: if a network line crosses it (or two arrive collinear from opposite sides), the inner node is computed from the arrivals —on the crossing line, at the intersection if there are two— and the others reach it following their axis with a short break. If no line crosses it (large vault, stubs, curves), each one ends at the edge and its box stays there: the user completes it by hand. Two conduits converging at a grazing angle start at a shared vertex on the main line; runs are split where the dashes deviate >0.75 pt so every vertex stays on the layer's line.",
    "Una línea CAD con deriva de 1–2 pt (dibujo casi recto) ya no sale como dos líneas superpuestas terminando en la misma bóveda: cada guión se asigna a la recta que mejor ajusta y las corridas superpuestas se funden. La línea que atraviesa una bóveda se importa como UNA sola polilínea con la bóveda de vértice (antes se partía en dos en el nodo).":
        "A CAD line with a 1–2 pt drift (almost straight drawing) no longer comes out as two overlapping lines ending at the same vault: each dash is assigned to the line that fits it best and overlapping runs are merged. The line crossing a vault is imported as ONE single polyline with the vault as a vertex (before it was split in two at the node).",
    "Paso «Capas de la hoja» antes de la vista previa: lista todas las capas del plano (con su cantidad de trazos) y permite mostrarlas u ocultarlas con casillas, viendo el resultado en vivo. Las capas ocultas no se dibujan en el lienzo ni se usan en el reconocimiento. Incluye buscador y botones Mostrar/Ocultar todas.":
        "«Sheet layers» step before the preview: it lists all the plan layers (with their stroke count) and lets you show or hide them with checkboxes, seeing the result live. Hidden layers are not drawn on the canvas nor used in recognition. It includes a search box and Show/Hide all buttons.",
    # ── v1.1.0 ──
    "Nuevo diseñador de Bancoductos (Duct Bank): dibuja la sección con envolvente, márgenes, redondeo de esquinas, reglas de separación y de resguardo al borde. Cada bancoducto se asigna a una utilidad del plano y al importar en Civil 3D se crea el sólido 3D del contenedor + los conductos internos como tuberías reales.":
        "New Duct Bank designer: draws the section with envelope, margins, corner rounding, separation and edge clearance rules. Each duct bank is assigned to a utility on the plan and, when importing into Civil 3D, the 3D solid of the container + the internal conduits as real pipes are created.",
    "Panel «Bancoductos» en el inventario derecho: lista todos los bancoductos del proyecto con botones Nuevo / Editar / Duplicar. Doble-click en una fila abre el diseñador ya cargado con ese bancoducto. Click derecho sobre una tubería del plano ofrece «Crear/Editar bancoducto».":
        "«Duct Banks» panel in the right inventory: lists all project duct banks with New / Edit / Duplicate buttons. Double-click on a row opens the designer already loaded with that duct bank. Right-click on a pipe offers «Create/Edit duct bank».",
    "Opción para elegir si se dibuja el contenedor 3D del bancoducto o solo los conductos internos (útil cuando el contenedor de concreto ya existe en el DWG).":
        "Option to choose whether the duct bank's 3D container is drawn or only the internal conduits (useful when the concrete container already exists in the DWG).",
    "Reglas de diseño OBLIGATORIAS: separación mínima entre conductos (2\") y resguardo al borde interior (3\") pre-cargadas por defecto. Si intentas colocar o mover un conducto violando la regla, se bloquea y aparece un banner rojo explicando qué falla.":
        "MANDATORY design rules: minimum separation between conduits (2\") and clearance to the inner edge (3\") preloaded by default. If you try to place or move a conduit breaking the rule, it is blocked and a red banner explains what fails.",
    "Botón «Mostrar medidas»: activa un overlay con las cotas rojas automáticas entre cada conducto y sus vecinos (o al borde del contenedor). Se apaga con Escape o volviendo a hacer click en el botón.":
        "«Show measurements» button: turns on an overlay with automatic red dimensions between each conduit and its neighbors (or to the container edge). It turns off with Escape or by clicking the button again.",
    "Silueta fantasma al dibujar conducto: al mover el mouse en modo «Dibujar conducto» aparece el conducto en verde si las reglas permiten colocarlo ahí, o en rojo si no. Un click coloca sólo cuando está verde.":
        "Ghost silhouette when drawing a conduit: moving the mouse in «Draw conduit» mode shows the conduit in green if the rules allow placing it there, or in red if not. A click only places it when it is green.",
    "Rejilla 1\"×1\" dentro del contenedor para orientarte a la escala real mientras diseñas.":
        "1\"×1\" grid inside the container to get oriented at real scale while designing.",
    "Escape en el diseñador: apaga «Mostrar medidas», o sale de la herramienta activa a Puntero, o deselecciona el conducto. Ya no cierra la ventana por accidente.":
        "Escape in the designer: turns off «Show measurements», or leaves the active tool back to Pointer, or deselects the conduit. It no longer closes the window by accident.",
    "Selector de idioma en Archivo → Opciones… La app se puede alternar entre Español e Inglés; la elección se recuerda al reabrir.":
        "Language selector under File → Options… The app can switch between Spanish and English; the choice is remembered on reopen.",
    "Diálogo de Opciones en el menú Archivo (pensado para crecer con más preferencias en el futuro).":
        "Options dialog in the File menu (designed to grow with more preferences in the future).",
    "Menú contextual (click derecho) en las tuberías del inventario: crear o editar el bancoducto asignado sin salir del contexto.":
        "Context menu (right-click) on inventory pipes: create or edit the assigned duct bank without leaving context.",
    "El botón «Abrir diseñador de Duct Bank» del panel principal siempre abre un diseño en blanco (para editar uno existente usa el panel «Bancoductos»).":
        "The «Open Duct Bank designer» button in the main panel always opens a blank design (to edit an existing one use the «Duct banks» panel).",
    "La cota invert del bancoducto ahora manda el FONDO del contenedor (parte inferior externa), como en las tuberías normales. Los conductos internos se distribuyen correctamente hacia arriba desde ese fondo.":
        "The duct bank invert elevation now drives the BOTTOM of the container (outer lower face), like normal pipes. Internal conduits distribute correctly upward from that bottom.",
    "Las cotas por tramo (VertexInv) del pipe padre ahora se aplican también al sólido del contenedor y a los conductos internos — antes solo se usaban en tuberías normales.":
        "Per-segment elevations (VertexInv) on the parent pipe now also apply to the container solid and internal conduits — previously used only on normal pipes.",
    "Zoom del lienzo principal: acercar hasta 4000% y alejar hasta 30% con la rueda o los botones (antes 1000% / 10% y el botón se saltaba el límite).":
        "Main canvas zoom: zoom in up to 4000% and out to 30% with the wheel or buttons (was 1000% / 10% and the button skipped the limit).",
    "El botón «+ Nuevo» del panel de bancoductos ahora sí crea uno desde cero (antes cargaba el último diseño).":
        "The «+ New» button in the duct banks panel now really creates one from scratch (previously loaded the latest design).",
    "Rediseño del diseñador de bancoductos: acciones «Cancelar / Guardar y cerrar» debajo del canvas, «Puntero» unificado (click selecciona, arrastra mueve), banner rojo sobre el canvas cuando hay problemas, panel «Identificación» al inicio, panel «Conducto» contextual (cambia entre modo nuevo/editar).":
        "Duct bank designer redesign: «Cancel / Save and close» actions below the canvas, unified «Pointer» (click selects, drag moves), red banner over the canvas when there are issues, «Identification» panel at the top, contextual «Conduit» panel (switches between new/edit mode).",
    "Modo oscuro mejorado: el bancoducto asignado a la tubería seleccionada ya se lee sin problemas, y el título en «Duct Bank: ...» dejó de salir con azul ilegible sobre fondo negro.":
        "Improved dark mode: the duct bank assigned to the selected pipe is now readable, and the «Duct Bank: ...» title no longer shows in an illegible blue on black background.",
    "Los tamaños de tubería que faltan en el catálogo se instalan automáticamente al importar (evita el fallback silencioso a un diámetro distinto).":
        "Pipe sizes missing in the catalog are automatically installed on import (prevents silent fallback to a different diameter).",
    "El redondeo de esquinas del bancoducto ahora sí se respeta en el sólido 3D de Civil 3D (antes se dibujaba siempre con esquinas rectas aunque en el diseñador se viera redondeado).":
        "The duct bank corner rounding is now respected in the Civil 3D 3D solid (before it was always drawn with square corners even if it looked rounded in the designer).",
    "Bancoductos con pendiente (invert distinto entre extremos) o secciones altas (H>W) ya se dibujan como sólido 3D. Antes fallaban en silencio y sólo aparecían los conductos internos.":
        "Sloped duct banks (different invert at each end) or tall sections (H>W) are now drawn as a 3D solid. Before they failed silently and only the internal conduits appeared.",
    "En curvas del path, el sólido del bancoducto y los conductos internos ahora comparten el mismo centro de curva (concéntricos): los cables ya no se salen del contenedor ni el contenedor de los cables.":
        "On path curves, the duct bank solid and the internal conduits now share the same curve center (concentric): cables no longer stick out of the container nor the container out of the cables.",
    "La tubería padre del bancoducto ya no se dibuja como cilindro 3D dentro del sólido (aparecía como un conducto fantasma extra en la cara inferior). Se sigue usando para generar los buzones en los extremos.":
        "The duct bank's parent pipe is no longer drawn as a 3D cylinder inside the solid (it appeared as an extra ghost conduit on the bottom face). It is still used to generate the manholes at the ends.",
    "En vértices con varios conductos, ya no se apilan varios buzones en el mismo punto — sólo uno por vértice.":
        "At vertices with several conduits, several manholes are no longer stacked at the same point — only one per vertex.",
    "Los conductos del bancoducto ya no sobresalen del contenedor en el render 3D (Civil 3D dibuja al diámetro exterior; ahora se fuerza pared 0 en las medidas custom que la app inyecta al catálogo).":
        "Duct bank conduits no longer poke out of the container in the 3D render (Civil 3D draws to outer diameter; now forces wall 0 for custom sizes the app injects into the catalog).",
    "Rediseñar el bancoducto de una utilidad ya no crea dos sólidos superpuestos: se sobreescribe por identidad, no por nombre.":
        "Redesigning a utility's duct bank no longer creates two overlapping solids: it overwrites by identity, not by name.",
    "El sólido del bancoducto sigue las cotas de la tubería padre (antes quedaba a Z=0 mientras los conductos usaban las cotas correctas).":
        "The duct bank solid now follows the parent pipe's elevations (previously stayed at Z=0 while conduits used the correct elevations).",
    "Al abrir el diseñador desde una tubería, ahora carga el bancoducto asignado a ESA tubería (antes cargaba el último editado).":
        "When opening the designer from a pipe, it now loads the duct bank assigned to THAT pipe (previously loaded the last edited one).",
    "Los conductos de 1\" muestran su medida con letra más grande para que sea legible (antes quedaba invisible por lo pequeño del círculo).":
        "1\" conduits show their measurement with a larger font so it is readable (before it was invisible because the circle was so small).",
    # ── v1.0.1 ──
    "Alineamientos curvos: el eje de la red sigue el mismo arco (mismo radio) que la tubería curva, en vez de cortar la esquina en recta.":
        "Curved alignments: the network axis follows the same arc (same radius) as the curved pipe, instead of cutting the corner in a straight line.",
    "Botón «Agregar tubería curva»: seleccionas dos tuberías y un radio opcional, y crea la curva tangente y redondea también el eje.":
        "«Add curved pipe» button: you select two pipes and an optional radius, and it creates the tangent curve and also rounds the axis.",
    "Selector de versión e idioma de Civil 3D en el toolbar; se guarda en el proyecto y se repone solo al reabrirlo.":
        "Civil 3D version and language selector in the toolbar; it is saved in the project and restored automatically when reopening it.",
    "Código de sistema de coordenadas (Huso) en la georreferenciación: el dibujo queda seteado con ese sistema al importar la red en Civil 3D.":
        "Coordinate system code (Zone) in georeferencing: the drawing is set to that system when the network is imported into Civil 3D.",
    "Botón «Opacidad» con deslizable para atenuar solo el PDF, y fondo blanco/negro detrás del PDF.":
        "«Opacity» button with a slider to dim only the PDF, and a white/black background behind the PDF.",
    "Georreferenciación: indicador de carga al buscar/descargar el mapa, e imanes a las esquinas redondeadas de las parcelas.":
        "Georeferencing: loading indicator when searching/downloading the map, and snapping to the rounded parcel corners.",
    "Familias por defecto: ahora se coloca la familia elegida (se emparejan por su GUID, no por el nombre traducido) — antes salía una familia distinta.":
        "Default families: the chosen family is now placed (they are matched by their GUID, not by the translated name) — before a different family came out.",
    "Buzones ocultos ya no aparecen como una estructura visible al importar la red.":
        "Hidden manholes no longer appear as a visible structure when the network is imported.",
    "Redes de presión: los codos salen a la elevación correcta (sobre el eje del tubo).":
        "Pressure networks: bends come out at the correct elevation (on the pipe axis).",
    "Cotas por tramo: ya no se pierden al cerrar y reabrir el proyecto, y la tabla ya no aparece en la pestaña Buzones.":
        "Elevations per segment: they are no longer lost when closing and reopening the project, and the table no longer appears in the Manholes tab.",
    "Georreferenciación: el ajuste ya no deforma el plano (transformación de similaridad) y el RMSE es real aunque uses 3 puntos.":
        "Georeferencing: the fit no longer distorts the plan (similarity transformation) and the RMSE is real even if you use 3 points.",
    "Las zonas borradas ya no aparecen en la ventana de georreferenciación.":
        "Erased areas no longer appear in the georeferencing window.",
    "Coordenadas mostradas como X, Y, Z (antes N, E), con 4 decimales; muestran el código de Huso si lo fijaste.":
        "Coordinates shown as X, Y, Z (before N, E), with 4 decimals; they show the Zone code if you set it.",
    "Los nombres de familias se muestran en el idioma del Civil 3D seleccionado.":
        "Family names are shown in the language of the selected Civil 3D.",
    "«Trazar centerline» va justo después de «Dibujar utilidad»; ejes X/Y de la georreferenciación en morado; ventana de georreferenciación maximizada al abrir.":
        "«Trace centerline» comes right after «Draw utility»; georeferencing X/Y axes in purple; georeferencing window maximized on open.",
    "Tema oscuro y accesibilidad; botones de eliminar en rojo; el membrete ya no se separa a una capa aparte.":
        "Dark theme and accessibility; delete buttons in red; the title block is no longer separated into its own layer.",
    "Función «Emparejar centerline dibujado» de la georreferenciación.":
        "Georeferencing «Match drawn centerline» function.",
    # ── v1.0.0 ──
    "Primera versión estable: digitalización PDF → DXF, importación a Civil 3D con familias imperiales de gravedad/presión/conduit, gestión de buzones y cajas, y adjunción automática de Property Sets a tuberías vía Excel.":
        "First stable release: PDF → DXF digitizing, import into Civil 3D with imperial gravity/pressure/conduit families, manhole and box management, and automatic attachment of Property Sets to pipes via Excel.",
}
