"""
model.py — Estructuras de datos y constantes del marcado.

El modelo vivo se guarda como listas de dicts JSON-serializables (compatibles con
los .digproj ya guardados). Aquí se centralizan las CLAVES de esos dicts, los
valores por defecto (factories) y los mapeos derivados. No importa Qt.

Esquema de cada elemento (claves de los dicts):
  pipe   = {layer, pts:[(x,y)…], ab:bool, name:str, diam:float, unit:"pulg"|"pies"}
  leader = {text, orient:"h"|"v"|"d", simple:bool, arrow:(x,y), tp:(x,y),
            font:str, size_ft:float, bold:bool, landing:(x,y)|None}
  text   = {pos:(x,y), text:str, size_ft:float, font:str, bold:bool, rot:int, free:bool,
            box:(x,y,w,h)  # solo textos de corrección OCR}
  region = {pts:[(x,y)…], enabled:bool}
  pipe (red gravedad) añade: inv_start, inv_end (float|None), part(str), frm, to (cod buzón),
        net(str nombre de red), world(bool), wstart/wend((x,y) reales si world)
  struct = {cod, x, y, rim:float|None, sump:float|None, part:str, part_size:str, net:str,
            world:bool, covered:bool, height_ft:float, curve:bool, radius_ft:float|None,
            hidden:bool}
  hidden=True: el usuario no quiere un buzón real en este vértice (p.ej. un
  vértice auto-detectado que en realidad no es un acceso físico). No se dibuja
  en el lienzo ni en el DXF/Civil3D como manhole visible — se exporta igual el
  punto (la red necesita el nodo para conectar tramos) pero con HIDDEN=1 en el
  XDATA, y el importador de Civil3D (ImportarRed.cs) usa ahí la familia
  "Estructura nula" (invisible, mantiene la topología) en vez de un buzón real.
  Cuando curve=True el struct no es un buzón/caja: es la ESQUINA de un elemento curvo
  (p.ej. el codo de un bancoducto). rim/sump/height_ft/part/part_size no aplican — la
  familia/tamaño de la curva SIEMPRE es la misma de la tubería recta que pasa por ese
  vértice (se muestra de solo lectura en la UI, no se elige aparte). radius_ft es el
  radio deseado en pies; vacío/0 = automático (ImportarRed.cs usa 6× el ancho/diámetro
  interior de la tubería). Se exporta al DXF como PDFCAD_CURVE en vez de PDFCAD_STRUCT
  (sin buzón), y la tubería lleva además NO_MANHOLE_VERTS marcando ese índice.
  ref_centerline = {cod, pts:[(x,y)…]}  — trazo de referencia de una calle,
  DISTINTO de una utilidad (no representa ninguna tubería): se dibuja aparte
  (tab "Centerlines") y sirve de referencia visual (e imán de puntos de
  control) al georreferenciar. Se exporta al DXF en su propia capa
  REF_CENTERLINES, sin XDATA.
Coordenadas DIBUJADAS en PÍXELES (se convierten con geometry.to_cad al exportar);
coordenadas IMPORTADAS de Excel ya son reales de mundo (world=True → se usan tal cual).
"""

VERSION = "1.2.0"

# Capas de red por GRAVEDAD (tramos entre buzones, con invert inicio/fin).
GRAVITY_LAYERS = {"ALCANTARILLADO", "DRENAJE"}

# UNIDAD DE TRABAJO para la red 3D. Solo dos opciones — pies o pulgadas — porque
# es lo que consume el plugin C# aguas abajo. NUNCA usar metros en el flujo de
# red 3D (ni en la UI, ni en el JSON, ni al ingresar cotas/diámetros).
WORK_UNITS = ("ft", "in")
DEFAULT_WORK_UNIT = "ft"


# DIÁMETROS de tubería: SIEMPRE en PULGADAS y SOLO de esta lista (los tamaños
# nominales del catálogo imperial de Civil 3D). No se permite un valor libre —
# así lo que se elige aquí coincide 1:1 con un tamaño real del catálogo y no cae
# al "más cercano" al importar. El diámetro es independiente de la unidad de
# trabajo (que rige coordenadas/cotas): el diámetro nunca va en pies.
PIPE_DIAMETERS_IN = [12, 15, 18, 21, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78,
                     84, 90, 96, 102, 108, 114, 120, 126, 132, 138, 144]

# MATERIALES de tubería permitidos en la UI. Son exactamente los valores del
# desplegable "Material" de Civil 3D, para que el plugin los setee 1:1 en la
# propiedad Material de cada tubería/estructura.
PIPE_MATERIALS = ["Material sin definir", "Hormigón armado", "Acero corrugado",
                  "Plástico ABS", "Fundición dúctil", "PVC"]
DEFAULT_PIPE_MATERIAL = "Material sin definir"


TIPOS = [
    ("Agua (W)", "AGUA"), ("Alcantarillado (SS)", "ALCANTARILLADO"),
    ("Drenaje (SD)", "DRENAJE"), ("Gas (G)", "GAS"),
    ("Eléctrico (E)", "ELECTRICO"),
    ("Telecomunicaciones (T)", "TELECOM"),
]
ACI_RGB = {1: (255, 60, 60), 2: (235, 215, 40), 3: (60, 210, 60), 4: (60, 210, 210),
           5: (90, 140, 255), 6: (230, 90, 230), 7: (235, 235, 235), 8: (150, 150, 150),
           30: (255, 150, 40)}
LEADER_TEXT_FT = 3.0
LEADER_ORIENT = [("h", "Horizontal"), ("v", "Vertical"), ("d", "Diagonal")]
Z_PDF, Z_ERASE, Z_MARK, Z_HANDLE = 0, 1, 5, 8
# Índices de las pestañas del inventario (derecha)
TAB_PIPE, TAB_ML, TAB_LEADER, TAB_TEXT, TAB_REGION, TAB_BZ, TAB_CURVE, TAB_CL, TAB_DB = 0, 1, 2, 3, 4, 5, 6, 7, 8

# Tipo de red derivado de la CAPA (agrupa las utilidades a nivel de red completa).
#   gravity  → red por gravedad con buzones (alcantarillado, drenaje)
#   pressure → red a presión (agua, gas)
#   conduit  → red de conductos (eléctrico/telefonía; aérea o subterránea)
NETWORK_KIND = {
    "AGUA": "pressure", "GAS": "pressure",
    "ALCANTARILLADO": "gravity", "DRENAJE": "gravity",
    "ELECTRICO": "conduit", "ELECTRICO_AEREO": "conduit",
    "TELECOM": "conduit", "TELECOM_AEREO": "conduit",
}
# Tipo por TUBERIA en el JSON de red 3.0:
#   "pipe"     → tramo dentro de una red con buzones (típico de gravedad)
#   "pressure" → línea a presión (sin buzones intermedios)
# Los eléctricos/telefonía por defecto se tratan como "pipe" (el plugin C# los usa así).
NETWORK_TYPE_DEFAULT = {
    "AGUA": "pressure", "GAS": "pressure",
    "ALCANTARILLADO": "pipe", "DRENAJE": "pipe",
    "ELECTRICO": "pipe", "ELECTRICO_AEREO": "pipe",
    "TELECOM": "pipe", "TELECOM_AEREO": "pipe",
}


MANNINGS_N = {
    "PVC": 0.009, "HDPE": 0.011, "PE": 0.011,
    "RCP": 0.013, "CONCRETO": 0.013, "CONCRETE": 0.013,
    "CLAY": 0.013, "ARCILLA": 0.013, "VCP": 0.013,
    "DIP": 0.011, "DUCTILE": 0.011, "HIERRO": 0.012,
    "CAST IRON": 0.012, "STEEL": 0.012, "ACERO": 0.012,
    "CMP": 0.024, "CORRUGATED": 0.024,
}
COVER_MIN_FT = {
    "AGUA": 3.0, "ALCANTARILLADO": 3.0, "DRENAJE": 2.5,
    "GAS": 2.0, "ELECTRICO": 2.0, "ELECTRICO_AEREO": 0.0,
    "TELECOM": 2.0, "TELECOM_AEREO": 0.0,
}


def mannings_n(material):
    """Coeficiente de Manning por material (fuzzy match).
    Cubre también los nombres de material en español de la UI/Civil 3D
    (Hormigón armado, Acero corrugado, Plástico ABS, Fundición dúctil, PVC)."""
    m = (material or "").upper().strip()
    # "corrugado/corrugated" (CMP) primero: su n es alto y no debe perder contra "acero".
    if "CORRUGAD" in m or "CMP" in m:
        return 0.024
    es = {
        "HORMIG": 0.013, "CONCRET": 0.013,        # hormigón / concreto
        "PVC": 0.009, "ABS": 0.011, "HDPE": 0.011,
        "FUNDIC": 0.011, "DUCTIL": 0.011, "DÚCTIL": 0.011,  # fundición dúctil
        "ACERO": 0.012, "STEEL": 0.012,
    }
    for k, v in es.items():
        if k in m:
            return v
    for k, v in MANNINGS_N.items():
        if k in m:
            return v
    return 0.013


def network_kind(layer):
    """Devuelve gravity/pressure/conduit según la CAPA de la utilidad."""
    return NETWORK_KIND.get(layer, "unknown")


def default_network_type(layer):
    """Valor por defecto de 'network_type' para una utilidad (pipe|pressure)."""
    return NETWORK_TYPE_DEFAULT.get(layer, "pipe")


CHANGELOG = [
    ("1.2.0", [
        ("added", "Reconocimiento de TELECOMUNICACIONES: en «Capas de la hoja» → «Utilidades a reconocer» aparece la casilla Telecomunicaciones (marcada por defecto). Lee las líneas subterráneas de telecom (C-TELE-UNGD existentes, a abandonar y propuestas), el alineamiento propuesto T-PROP-COMM y el banco de ductos de comunicaciones de Metro («—SC—»), con sus abandonadas. Es red de conductos, como el eléctrico: se pone caja solo donde el plano tiene una bóveda o manhole, con sus medidas. Las letras del linetype («t», «TE», «SE») ya no se toman por pedazos de línea: probado en las 67 hojas con telecom de los 4 PDFs, sin tramos inventados. Las líneas aéreas (C-TELE-OVHD) no se importan."),
        ("fixed", "Gas: la misma línea existente que el plano trae repetida por otros xrefs (capas C-NGAS-UGND-E y C-NGAS-UGND-E-ADD con la misma geometría) se importaba dos o tres veces superpuesta; ahora entra una sola vez (19 líneas repetidas menos en los 4 PDFs de prueba). Las demás utilidades no cambian."),
        ("fixed", "«//» en tramos cortos: una línea con su doble barra propia a lo largo ya se importa abandonada (AB) aunque cerca de una T o un quiebre el plano ponga las marcas más seguidas de lo normal (AutoCAD dibuja el linetype por tramo). Reportado en DU08 hoja 21 (gas «-D»); corrige también 3 líneas eléctricas «-D» del LABOE y 1 de agua del DU08. Nada más cambia en los 4 PDFs de prueba."),
        ("added", "Reconocimiento de GAS: en «Capas de la hoja» → «Utilidades a reconocer» aparece la casilla Gas (marcada por defecto, como las demás). Lee las líneas de gas existentes (capas C-NGAS-A/-D/-E), las propuestas (C-NGAS-UNGD-N, PROP-GAS-ALGN) y las variantes de otros paquetes, con sus abandonadas («/» en la capa -A, «//» en cualquiera). Es red a presión, como el agua: se importan las líneas sin cajas automáticas. La letra «G» del linetype ya no desvía la línea: probado en las 68 hojas con gas de los 4 PDFs, sin tramos inventados."),
        ("changed", "Divisores más fáciles de arrastrar: entre el plano y el panel lateral (vista previa del reconocimiento, «Capas de la hoja», hoja compuesta) hay ahora una agarradera visible que se ilumina en azul al pasar el ratón o arrastrar; en la ventana principal, el borde de los paneles laterales también se marca y se ilumina."),
        ("changed", "Asistente de reconocimiento: al abrir un PDF, las cuatro utilidades (Eléctrico, Drenaje, Agua y Alcantarillado) vienen marcadas por defecto en «Capas de la hoja»; desmarca las que no quieras reconocer."),
        ("changed", "Vista previa del reconocimiento: la cobertura se muestra como una barra de 0 a 100 % (verde si está completa, ámbar o roja si faltan guiones), con los guiones sin cubrir y los trazos fuera de patrón como marcas de color debajo."),
        ("fixed", "Extremo con extremo sin altura para una tubería vertical: cuando dos tuberías de la misma utilidad a presión terminan en el mismo punto a distinta cota, pero la diferencia es muy chica para dos codos y una vertical (p. ej. 0.15 ft cuando hacen falta 3.19 ft en Ø12\"), aparece el triángulo rojo avisando que no hay espacio para una vertical (el texto de las alertas y marcadores del lienzo ahora sale en un bloque de ancho medio, no en una línea larga). En Civil 3D ya no quedan sin unir: la tubería más larga toma una pendiente para llegar a la más corta y se unen con un codo; si las dos miden lo mismo, las dos van a un punto medio."),
        ("fixed", "Tee, Wye y cruz con tubos de distinto diámetro (p. ej. tronco Ø24 y ramal Ø12 a la misma cota de fondo): las bocas ya encajan en sus tubos. La pieza se centraba en el promedio de los ejes y así ninguna boca quedaba coaxial (el tronco entraba torcido y el ramal quedaba por debajo de su boca). Ahora se centra en el eje del tubo más grueso y cada brazo más delgado va a la altura de SU tubo, dentro del cuerpo (fondo plano, sin cambiar ninguna cota). Si el desnivel es tan grande que el brazo no cabe en el cuerpo, se prioriza que conecte: la punta del tubo se lleva a la boca."),
        ("fixed", "Codo con reducción (dos tuberías de distinto diámetro que giran, p. ej. Ø24→Ø12 a 45°): en vez de un codo que se estrechaba a lo largo de la curva, Civil 3D pone un codo UNIFORME del diámetro mayor en el vértice y, pegada a su boca, una REDUCCIÓN excéntrica hacia el tubo chico. El codo se centra en el eje del tubo grande y la reducción une el eje de cada tubo tal como está dibujado (con la misma cota de fondo sale de fondo plano), así las bocas quedan a ras de los tubos y no se cambia ninguna cota. La reducción también lleva su Property Set (tipo «Reducción»). El mensaje del lienzo lo indica: «un codo sólido de 24\" con reducción 24×12\"»."),
        ("fixed", "Codos cerrados con un tramo corto (la tubería vuelve casi en U y el tramo no alcanza para la curva, p. ej. 170° con 2 ft): aparece el triángulo rojo con lo que necesita el codo y lo que mide el tramo. En Civil 3D ya no queda el codo por un lado y el tubo corto suelto: se pone un codo de retorno (curva en U) justo en el vértice y el tramo corto se corre hacia el costado lo mínimo para no montarse sobre el otro tubo (~1.2 ft en Ø12\"), conservando su largo y dirección."),
        ("changed", "Integración con la rama de reconocimiento (Agua, Alcantarillado, Drenaje y Eléctrico): en líneas eléctricas y de telecomunicaciones reconocidas del PDF, la app pone caja (CAJA-) SOLO donde el plano tiene una bóveda real, con sus medidas; los quiebres y esquinas ya no llevan caja (antes salían ~55 cajas por hoja, ahora ~5). Al dibujar a mano siguen sin cajas automáticas. Los codos reconocidos en eléctrico conservan su radio (CV) aunque no haya caja en ese vértice, y una bóveda que cae sobre un vértice ya existente de la línea queda marcada como bóveda."),
        ("fixed", "Idioma: las listas del panel derecho ya se traducen. La lista de utilidades mostraba el código interno de la capa («AGUA», «DRENAJE»…) aunque la app estuviera en inglés; ahora muestra el tipo en el idioma elegido («Agua»/«Water», «Drenaje»/«Storm Drain»…) y cambia al instante con el idioma. También se traducen la orientación de los leaders, «(sin familia)», los mensajes del panel «Mover con precisión» y la lista de bancoductos."),
        ("added", "Accesorios sólidos con Property Set real: cada codo, Tee, Wye y cruz que crea el plugin trae el Property Set «PDFCAD_Accesorio», visible en Civil 3D en Propiedades → Extended Data, con Tipo_Accesorio, Angulo_Grados, Diametro_Pulg, Material y Cota_Eje_Pies. Sirve para filtrar, etiquetar y sacar cómputos. Antes esos datos solo iban como XDATA, que Civil 3D no muestra. Para dibujos importados antes, el comando PS_ACCESORIOS se los agrega."),
        ("changed", "Manual de usuario rediseñado: ahora se lee por capítulos cortos, con índice a la izquierda, botones «Anterior / Siguiente» y letra más grande o más pequeña (A+ / A−, se recuerda). Explica todo paso a paso y en lenguaje sencillo, con consejos y avisos destacados, e incluye una leyenda con los símbolos reales del lienzo y una tabla de cuándo sale cada alerta roja y qué hará Civil 3D. Respeta el modo claro/oscuro y está en español e inglés."),
        ("fixed", "Corregido: al editar cualquier campo de una utilidad sin tamaño de catálogo (por ejemplo, el nombre), su diámetro quedaba en 0 y cambiaban las alertas del lienzo (un aviso rojo podía volverse ✓). Ahora se conserva el diámetro. Además, los mensajes de alertas y cruces nombran cada utilidad como «Agua - nombre de la red» (o solo «Agua» si no tiene nombre)."),
        ("fixed", "Conexión vertical aprobada en un quiebre con poco desnivel: cuando una utilidad pasa con un quiebre y la otra termina ahí, pero el desnivel no alcanza para bajar con dos codos de 90° (3.14 diámetros + 0.05 ft), aparece el triángulo rojo avisándolo. En Civil 3D ya no se deja sin conectar: se pone una Wye con el ramal inclinado y la tubería que termina se modifica para llegar a ella con pendiente (sin tubo auxiliar, codos ni vertical)."),
        ("fixed", "Codos muy juntos en redes a presión: si entre dos codos queda un tramo más corto que 3 diámetros (mínimo 1 ft), aparece el triángulo rojo avisando que es muy corto y que en Civil 3D se reemplazará por un solo codo. El plugin ya no dibuja los dos codos montados uno sobre otro: une los dos quiebres en uno solo, en la intersección de los tramos vecinos (mismo giro total) y a la cota promedio."),
        ("fixed", "Uniones de una misma utilidad a presión: donde dos tuberías se juntan a la misma cota (una termina sobre la otra o comparten vértice), el mensaje del lienzo ya no habla de «conflicto»: dice en pocas palabras qué hará Civil 3D (por ejemplo «una Wye sólida en la red «RED-GAS»»). Si tienen nombres de red distintos ya no sale la alerta roja de «redes distintas»: el plugin las mete en la misma red (la del primer nombre) y las une con el accesorio. La alerta roja queda solo para utilidades distintas (agua × drenaje)."),
        ("fixed", "Idioma inglés completo: al cambiar de idioma, TODOS los textos cambian al instante — menús, barra de herramientas, paneles, pestañas, listas desplegables, tooltips, diálogos y sus botones, avisos del lienzo, mensajes del instalador de familias, validaciones del diseñador de bancoductos y avisos del reconocimiento. El manual y el historial de versiones también están en inglés. Antes quedaban cerca de 400 textos en español y algunos paneles no se actualizaban hasta reabrir la app."),
        ("added", "Alerta de redes distintas: cuando dos utilidades de redes diferentes (por ejemplo agua y drenaje, o dos redes de agua con distinto nombre) se cruzan a la misma cota, el triángulo rojo reemplaza al círculo de conflicto y avisa que en Civil 3D no se conectarán y quedarán chocando."),
        ("added", "Alerta de escalón de cota: si en un vértice de una misma tubería a presión el tramo que llega y el que sale tienen cotas distintas (por ejemplo, editadas en «Cotas por tramo»), aparece el triángulo rojo. Al hacer clic explica que Civil 3D no puede dibujar ese escalón y que unirá los dos tramos en la cota promedio. En drenaje y alcantarillado no aparece: ahí el escalón es una caída válida en el buzón."),
        ("added", "Nueva advertencia en el lienzo: un triángulo rojo con «!» blanco marca los puntos donde se juntan 5 o más tuberías de una red a presión (agua, gas) a la misma cota. Civil 3D no puede unir tantas con un accesorio, así que ahí no se dibujaría ninguna pieza. Al pasar el mouse o hacer clic dice «Hay N tuberías en el mismo punto, no se dibujará ningún accesorio en Civil 3D, por favor corrija el dibujo». Reemplaza a los círculos de conflicto que antes se apilaban en ese punto. En drenaje y alcantarillado no aparece: ahí el buzón acepta los tubos que haga falta."),
        ("fixed", "Snap al dibujar utilidades: el marcador verde vuelve a verse siempre y ahora su FORMA dice a qué se engancha — círculo = extremo, cuadrado = vértice, triángulo = punto del tramo. La barra de estado lo confirma con un texto («⊙ Snap a vértice de «AGUA»»), útil cuando el marcador se pierde de vista con zoom bajo. Además, junto a un vértice el punto ya no se desliza unas décimas sobre el tramo: los vértices tienen prioridad, así las utilidades empalman exactamente donde se ve el marcador."),
        ("added", "Nuevo lienzo en blanco (Archivo → «Nuevo lienzo…», Ctrl+N): ya no hace falta un PDF para empezar un proyecto. Se elige el tamaño de hoja (A0–A4, Carta, Oficio, Tabloide, ANSI A–E, ARCH C–E o medidas a mano en mm/pulgadas), la orientación y la escala del plano (1\"=10', 20', 30', 40', 50', 60', 100', 200' o personalizada). El diálogo muestra cuánto terreno real abarca la hoja con la escala elegida. Dibujar, guardar el proyecto y exportar a DXF funcionan igual que sobre un PDF."),
        # ── Bloque Deyvy: curvas reales, bancoductos, cruces, Wye AWWA Steel ──
        ("fixed", "Bancoductos en Civil 3D 2027 (inglés): los conductos internos ahora se dibujan como cilindros 3D con el diámetro EXACTO que definiste (Ø1\", Ø2\", Ø3\", Ø4\", etc.). Antes, el catálogo de C3D rechazaba diámetros no estándar (por ejemplo Ø1\") y sumaba el espesor de pared, haciendo que los conductos se solaparan y sobresalieran de la envolvente."),
        ("added", "Validación en vivo del radio de curva: al seleccionar un elemento curvo, el campo «Radio (Pies)» muestra en rojo el máximo permitido por la geometría (tramos rectos adyacentes). El campo no deja escribir un valor mayor, y si el valor guardado excede el nuevo máximo, se ajusta automáticamente con un aviso explicando por qué."),
        ("added", "Uniones tipo Y (Wye) reales: al importar redes de presión con junturas de 3 tuberías en ~120°, el plugin ahora carga automáticamente las familias Wye (30/45/60/75/90°) del catálogo Imperial_AWWA_Steel a la PressurePartList activa y coloca la pieza real correspondiente. Funciona en Civil 3D 2025/2026/2027 en español o inglés (detecta la carpeta de idioma instalada)."),
        ("added", "Detección automática de cruces físicos de utilidades en el lienzo: cada punto donde un tramo de una utilidad CRUZA (no comparte extremo) otro tramo aparece con un círculo amarillo con «!» rojo. Sirve para revisar profundidades cuando dos utilidades se pasan por encima/debajo sin ser una juntura. Tooltip indica qué capas se cruzan; contador en la barra de estado. Se puede ocultar con el toggle «Mostrar cruces/conflictos» del menú Ver."),
        ("added", "Snap suave al dibujar utilidades: cuando el cursor se acerca a una utilidad EXISTENTE del mismo tipo (extremo, vértice intermedio o cualquier punto del tramo), aparece un círculo verde marcando dónde se pegaría el click. Si el primer click se pega al EXTREMO de otra utilidad del mismo tipo, la app pregunta si quieres «unirla como parte de esa utilidad» o «crear una utilidad nueva que la toca» (juntura automática al importar)."),
        # ── Bloque Santos: composición de hoja, reconocimiento eléctrico, bóvedas ──
        ("fixed", "Continuidad de las líneas de alcantarillado (reportado por el usuario en la hoja compuesta DU06 13+14): la principal ya no se corta junto a un lateral que toca la punta de uno de sus guiones — antes se cosían como esquina y la principal quedaba partida en el hueco del linetype; ahora la principal sigue de frente y el lateral llega a ella en el cruce exacto (también con huecos anchos y a pocos pt de un buzón). La línea tampoco se corta en cada «ss» de una curva ni en cada «//ss»: el trozo de línea entre el «//» y las letras ya no se lee como parte de la letra (DU08 h.37/38: las líneas «a abandonar» salen enteras de buzón a buzón y, por su «//», abandonadas). Sin tramos sin tinta ni en «V» en los 4 PDFs de prueba; eléctrico, drenaje y agua sin cambios."),
        ("fixed", "Precisión de las líneas de alcantarillado (reportado por el usuario en DU06 h.13): un lateral que llega a la principal justo en el hueco de su linetype ya no se inclina hacia el centro del hueco (quedaba 2 pt al costado de su tinta); el nodo va al cruce exacto de las dos rectas. Un guión corto del medio de una línea que se curva ya no se prolonga por encima del guión siguiente hasta el buzón (salían dos tramos casi superpuestos). Una tubería dibujada como contorno (rectángulo delgado) se toma por su eje en vez de dar la vuelta al rectángulo. Y una línea continua de un solo trazo ya no se descarta como «ruido» por una diferencia de redondeo de décimas de punto (recupera, p. ej., un lateral de drenaje propuesto en DU10 h.17 y 18 tramos cortos de agua que se perdían). Auditoría nueva de precisión (scripts/audit_alcantarillado.py): cada tramo contra los guiones de su propia capa; 0 tramos sin tinta y 0 desvíos salvo los ejes de tuberías con doble línea."),
        ("added", "Reconocimiento de ALCANTARILLADO (sanitario): en «Capas de la hoja» → «Utilidades a reconocer» aparece la casilla Alcantarillado (se activa si la hoja tiene capas C-SSWR; las cuatro casillas van ahora en dos columnas para que no se corten los nombres). Líneas: C-SSWR-UNGD-A/D/E/N (también -E-ADD y C-SSWR-UGND-N); buzones: V-SSWR-MANH, C-SSWR-STRC y los buzones propuestos C-SSWR-UNGD-STRC-N-###. Es red por GRAVEDAD como el drenaje: al importar, los buzones reconocidos entran como estructuras CIRCULARES con su diámetro (≈5 ft), y el DXF los exporta con SHAPE=circle y WIDTH_FT. El anillo del buzón que el plano dibuja en la propia capa de la tubería se toma como contorno del buzón (antes habrían salido 156 «tuberías» circulares en los PDFs de prueba) y una línea solo entra a un buzón redondo si su recta toca el círculo, no la caja que lo encierra. Auditoría en 4 PDFs (71 hojas con alcantarillado): ningún tramo sin tinta del plano debajo, ningún vértice en «V», cobertura ≥ 99.8 %; Eléctrico, Drenaje y Agua sin un vértice de diferencia."),
        ("fixed", "Reconocimiento determinista: cuando en un mismo símbolo de bóveda empataban dos capas (p. ej. poste y estructura), la capa asignada —y con ella si la bóveda se importa— cambiaba de una ejecución a otra. Ahora en empate manda la capa del contorno más grande del símbolo. Y el aviso «No se encontraron líneas…» nombra la utilidad correcta (decía «de drenaje» también en agua)."),
        ("added", "Los avisos de «Revisar» de la vista previa son cliqueables: un clic lleva la vista al lugar de la hoja (codo aproximado, curva que queda como polilínea, guion sin cubrir, bóveda sin línea, línea de capa «-A» sin patrón, «a abandonar», «/» en capa activa) con zoom y lo marca con un recuadro ámbar que parpadea; cada clic va al siguiente caso y la fila muestra cuál es (1/N). En «Detalles» también se pueden ubicar las abandonadas, los leaders y las bóvedas. No cambia nada del reconocimiento."),
        ("changed", "Vista previa del reconocimiento más visual y con menos texto: arriba cuatro tarjetas con las cifras (tramos, abandonadas, codos, estructuras) y una barra por utilidad a la misma escala (activas en sólido, abandonadas rayadas, del color de la utilidad; al pasar el mouse muestra el detalle). Debajo, «Revisar» lista solo lo que pide una decisión (bóvedas sin línea, curvas que quedan como polilínea, capas «-A» sin patrón…) en una línea corta con icono; el texto completo aparece al pasar el mouse. Lo informativo (trazos repetidos, rutas, letras omitidas…) queda plegado en «Detalles», agrupado por utilidad."),
        ("changed", "El doble slash «//» marca la línea como ABANDONADA en cualquier utilidad (Eléctrico, Drenaje y Agua) y en cualquier capa, aunque no sea de estado «-A» (p. ej. las «-D» «a abandonar» del DU08, reportado en Agua h.21). El paso entre «//» se aprende del plano igual que el de la «/», y un «//» suelto intercalado (el de un ramal junto a una T) ya no hace que una línea larga se importe activa. La «/» simple sigue exigiendo la capa «-A». La vista previa avisa cuántas líneas se marcaron abandonadas por el «//» fuera de una capa «-A»."),
        ("added", "Componer hoja de trabajo: al abrir un PDF vectorial se elige la hoja, se marca el área del plano que interesa y se «toma» a una hoja compuesta, como un XREF. Se pueden tomar piezas de varias hojas y de otros PDF, girarlas, corregir su escala y acomodarlas con el imán (los extremos de las líneas se pegan a los de la pieza vecina). Cada pieza conserva sus vectores, capas, textos y medidas; la hoja compuesta es un PDF real de una sola página con todas las capas, y el reconocimiento corre una sola vez sobre ella, así las líneas que cruzan de una hoja a otra salen como una sola ruta."),
        ("added", "En el compositor, los extremos de línea en el borde de cada pieza se marcan con un punto y los «Puentes» unen cada extremo con el que tiene enfrente en la pieza vecina (misma capa, hueco máximo configurable) con un trazo vectorial en esa misma capa: así se puede recortar cada hoja por dentro de su match line, sin la línea divisoria, y el reconocimiento sigue la utilidad de una pieza a la otra como una sola ruta. El imán también alinea piezas separadas por un hueco (deja los extremos en línea sin cerrarlo)."),
        ("added", "«Imán a líneas» en el área a tomar: al arrastrar el rectángulo (lados, esquinas o el área entera) sus lados saltan a las líneas generales de la hoja — match lines (también a guiones), marcos y bordes largos — y la guía usada se resalta en celeste. Entre varias a tiro gana la más larga."),
        ("fixed", "Precisión del reconocimiento en quiebres suaves y bóvedas: la simplificación de quiebres blandos baja de 1.5 a 0.5 pt, así la centerline ya no se aparta de los guiones hasta 1.5 pt en las transiciones (DU06 hoja 14: desvío p90 de 0.83 a 0.28 pt)."),
        ("added", "«Sin línea de borde» (activo por defecto): al tomar un área, cada lado se lleva al CENTRO de la línea larga que corra pegada a él (match line, marco de la vista), sea de la capa que sea y aunque vaya a guiones gruesos, y su tinta se tapa con una franja blanca. Así no se pierde ningún vector (los de debajo de la línea siguen ahí para el reconocimiento) y dos hojas contiguas se unen borde con borde sin hueco ni línea divisoria. Las grillas (series de paralelas) no cuentan."),
        ("added", "Codos reconocidos como esquina + radio: cuando los vértices de un codo caen sobre un círculo y las rectas que llegan y salen son tangentes a él, la ristra se sustituye por la esquina (intersección de tangentes) y la CAJA de ese vértice pasa a ser una esquina curva «CV» con `radius_ft` — el mismo modelo del dibujo manual, con el que el plugin genera la tubería curva tangente en Civil 3D. La vista previa dibuja el arco sobre la curva del PDF, las tangentes punteadas y la esquina. Solo cuenta como arco lo que el PDF dibuja como trazo curvo (Béziers / trazo continuo); una cadena de guiones rectos con quiebres se queda como esquinas, y las curvas suaves (giro < 8°) o sin recta tangente quedan como polilínea: no se inventa nada."),
        ("added", "Bóvedas abandonadas: el contorno que va dibujado en la propia capa de estado «-A» (lazo cerrado de 4 corridas) se reconoce como bóveda con contorno, medidas y giro, igual que las activas; la vista previa la marca «(AB)» y la CAJA que la línea abandonada deja en su borde recibe esa geometría al importar."),
        ("added", "Líneas abandonadas con «//»: además de la barra simple, se reconoce el doble slash como marcador — dibujado como dos barras sueltas o como un solo trazo en zigzag — y también barras más largas (hasta 18 pt) siempre que crucen la línea por su interior o la línea siga a ambos lados; el tick «|» que remata un tramo no se toca. Un trazo en zigzag con giros > 60° ya no se confunde con un codo."),
        ("changed", "Una línea es abandonada solo si se cumplen las dos cosas: está en la capa de estado «-A» Y sigue el patrón de marcadores «/» en toda su longitud (el paso entre marcadores se aprende del propio plano con ≥3 marcadores seguidos a la misma distancia; cada línea se juzga sola y los ramales más cortos que el paso heredan el veredicto de su capa). Dos barras sueltas no hacen una abandonada, ni el nombre de la capa por sí solo. La vista previa avisa de las líneas de capa «-A» sin patrón (se importan activas) y del patrón «/» hallado en una capa activa (manda la capa; revisar)."),
        ("changed", "Vista previa: las bóvedas huérfanas (cajas propuestas de otro paquete, cajas de paso, postes) van como marca discreta sin contorno ni medida, y un símbolo con lado menor de 2 ft no se mide como bóveda."),
        ("added", "Bóvedas eléctricas con su geometría real: el reconocimiento toma del PDF el contorno del símbolo (rectángulo con su giro, o círculo) y sus medidas en pies; la vista previa las dibuja con el color de la utilidad (el mismo de las cajas del editor) y «ancho × largo ft», y al importar la CAJA correspondiente guarda forma, medidas y contorno, que se dibuja a escala en el lienzo (la medida aparece al seleccionarla). El DXF exporta SHAPE, WIDTH_FT, LENGTH_FT y ROT_DEG en la estructura. Nada se inventa: las bóvedas sin línea que las atraviese no crean buzón."),
        ("fixed", "Líneas eléctricas muy cercanas: una línea que terminaba a ≤3 pt de otra paralela se enganchaba como ramal (T) y quedaban interconectadas. La convergencia rasante ahora exige que la línea realmente se acerque a la otra. Auditoría con paralelas hasta 2 pt (0.56 ft a 1\"=20'): se mantienen separadas."),
        ("changed", "Pantallas pequeñas: en el compositor cada panel se puede plegar a una tira (botón ‹ en su cabecera) para dar sitio a los demás, el ancho inicial de los paneles es proporcional a la ventana y se recuerda, y el texto de ayuda se oculta en ventanas estrechas. «Capas de la hoja» y «Vista previa del reconocimiento» abren maximizadas y su panel derecho va en un divisor arrastrable (ancho según la pantalla, nunca más del 32 %). El minimapa es más pequeño (150 × 110)."),
        ("fixed", "Costura del compositor alineada por la MATCH LINE: las dos hojas contiguas dibujan la misma raya de la costura, así que al pegar las piezas el imán las hace coincidir exactamente (sus extremos son la referencia). Antes, si cada hoja se recortaba a distinta altura —el imán de líneas del panel 2 engancha una guía distinta en cada una—, el desfase (decenas de pt) se quedaba tal cual y el plano salía escalonado: las líneas que cruzan no seguían derechas. El imán ya no depende de dónde se suelte la pieza: en el DU06 (hojas 13, 14 y 15) cae siempre en la misma posición, la correcta, aunque se suelte 70 pt descolocada. Si no hay match line, se usan los extremos de línea enfrentados, pero solo cuando al menos tres coinciden (una pareja suelta puede ser el guión equivocado y dejaba la costura corrida media raya)."),
        ("fixed", "Reconocimiento sin líneas inventadas cuando las líneas van muy juntas o se juntan (DU08 h.21, reportado por el usuario). (1) Trazos repetidos: algunos planos traen la MISMA capa dibujada dos veces (el xref insertado dos veces); cada guión se unía con su gemelo y salían líneas de ida y vuelta, y el tick de fin de tramo contaba doble y se prolongaba 30–40 pt sin tinta hasta la línea paralela (el tramo diagonal inexistente). Ahora cada trazo idéntico se usa una sola vez, y una línea cortada por la letra «E» del linetype sigue de corrido. (2) Dos líneas que se juntan (ramales de una «Y», curvas que convergen a un haz, dos ramales que llegan en T a la misma línea) ya no se cosen en una «V»: cada una sigue su propia trayectoria y termina donde el plano la termina. Una sola línea nunca se devuelve sobre sí misma (ángulo interior < 73°; medido en los 4 PDFs de prueba: las falsas ≤69.5°, las esquinas reales ≥77°). (3) Una curva ya no «retrocede» sin tinta para formar una esquina. En las hojas de DU08/DU10/LABOE los vértices en «V» pasan de 863 a 0 y ningún tramo queda sin tinta del plano debajo; el DU06 queda igual salvo tres microtramos de ida y vuelta junto a bóvedas."),
        ("fixed", "Reconocimiento: una curva que el plano dibuja en dos trazos con la punta compartida junto a una bóveda llega a la bóveda como UNA sola línea (antes la primera mitad se prolongaba por su recta hasta el borde y aparecían dos líneas). Y una línea que muere sobre otra (en T) ya no se «apropia» del trozo de enfrente cuando ese trozo es la continuación de una tercera línea (unida por la letra del linetype): así no se inventa un nodo sin tinta donde no llega nada (DU08 h.21, reportado por el usuario)."),
        ("fixed", "Reconocimiento: ticks «|» de fin de línea sin tramos inventados (DU08 h.49, reportado por el usuario). Un tick o una patita suelta ya no se estira sobre papel en blanco hasta formar una esquina (la «T» inexistente); solo cruza un hueco más largo que medio espacio del linetype si en ese hueco está la letra de la capa. Dos líneas que terminan cada una en su tick, pegados, se ven como dos T (el tick corto de una ya no se descartaba como ruido). Y el último tramo recto de una curva que termina cruzando otra línea ya no se confunde con una barra «/» de línea abandonada: la curva llega a su T y no se une a una patita cercana."),
        ("fixed", "Reconocimiento en el borde de la vista (DU08 h.49, reportado por el usuario): cuando la referencia viene recortada justo en el marco de la vista, (1) las líneas que llegan al borde se dibujan completas hasta su punta (extremo «cortado»), sin pegarse como T a una línea que cruzan antes; (2) un guión dibujado SOBRE el borde ya no se descarta por quedar una fracción de punto fuera (la línea llega hasta donde termina); y (3) las letras del linetype partidas por el recorte (media «E», medias barras «//») ya no se leen como tramos de línea: se reconocen porque el mismo grupo de astas se repite a lo largo de la línea. Vale para todas las utilidades."),
        ("added", "Reconocimiento de AGUA: en «Capas de la hoja» → «Utilidades a reconocer» aparece la casilla Agua (junto a Eléctrico y Drenaje; se activa si la hoja tiene capas de agua y por defecto sigue la selección de siempre). Reconoce las centerlines C-WATR-UNGD-* (existente, nueva, abandonada «-A», a abandonar «-D», acometidas «-SHORT», «_UGND-E-ADD», C-WATR-PIPE/-LTRL) con el mismo motor que eléctrico y drenaje; anotación, camisas, válvulas, medidores e hidrantes no son línea, y las bóvedas/pozos (V-WATR-VALT/MANH/STRU) se ven en la vista previa. Se importa como red a PRESIÓN (capa AGUA), igual que el agua dibujada a mano: sin cajas automáticas. El perfil de agua añade tres reglas propias (no afectan a eléctrico ni drenaje): puntas que el PDF dibuja unidas se unen primero entre sí (acometidas con quiebre), un hueco no se cruza en línea recta si la tinta dobla ahí (escalón), y las barras «/» se reconocen también sobre trazos curvos. Auditoría: 68 hojas de los 4 PDFs de prueba, ningún tramo sin tinta, ninguna «V», cobertura ≥ 99.9 %; eléctrico y drenaje sin un vértice cambiado."),
        ("added", "Capas según el estándar BOE (Los Ángeles «CADD Standards», basado en AIA/NCS): además de los nombres que ya usan los planos APDU (se reconocen exactamente igual), ahora también se reconocen como drenaje C-STRM-UGND («underground») y C-STRM-PIPE(-RCON/-CMTL…) con sus buzones C-STRM-MHOL y cabezales C-STRM-HWAL; en eléctrico, C-ELEC-…-MHOL. Se acepta la disciplina de nivel 2 (CU-STRM-… = Civil Utilities) y el relleno «~» de los grupos (C-GAS~-…). Los datos extendidos leen las 21 disciplinas, los códigos de estado y fase del estándar (A abandonada, D existente a demoler, E existente, F futuro, M a retirar, N nueva, T temporal, X fuera de contrato, 1–9 fases), materiales (RCON, CMTL, STEL…), números de vista (A001) y el sufijo de paquete (__UA2-3)."),
        ("added", "Datos extendidos: botón verde «Ver datos extendidos» junto a «Eliminar» (utilidades y buzones/estructuras). Abre una tabla Campo | Valor, como los Property Sets de Civil 3D. Lo reconocido del PDF trae, bloqueado y solo como referencia, la capa de la que salió (p.ej. `C-STRM-UNGD-N`) y lo que dice su nombre: disciplina (C = Civil), sistema (STRM = pluvial, ELEC…), ubicación (UNGD = subterránea), estado (N nueva, E existente, A abandonada, D a demoler), modificadores (MANH buzón, CTCH-BASN sumidero…) y el PDF/hoja de origen. La línea sigue siendo Drenaje o Eléctrico como siempre. Debajo puedes agregar tus propios campos (observación, contratista…). Todo se guarda en el proyecto y se exporta al DXF como XDATA (`XD_*` los del PDF, `XDU_*` los tuyos)."),
        ("fixed", "Costura sin «grada»: al unir dos hojas contiguas, las líneas que cruzan la costura (sobre todo las inclinadas) ya no quedan escalonadas. La pieza se coloca con el propio dibujo: A TRAVÉS de la costura hacen coincidir las dos match lines (la raya gruesa; se ajusta como recta porque suele ir algo inclinada, y una cota fina que corre al lado no cuenta), y A LO LARGO mandan los vectores que las dos hojas comparten junto a la línea, que son idénticos en ambas (si no comparten ninguno, la continuidad de las líneas que cruzan la costura). «Sin línea de borde» también encuentra la match line si el área quedó unos pt antes de ella (antes faltaba ese trozo de plano: grada de 8 pt en DU06 13→14), prefiere la raya gruesa a las cotas finas de al lado y la alcanza aunque el área llegue al marco de la hoja; el imán del área también prefiere la match line gruesa a la cota. Auditoría de los pares contiguos de los 4 PDFs de planos (recorte corto, justo, largo, sobre la cota o el marco; pieza soltada ±30 pt): el mismo punto del plano cae en el mismo lugar desde las dos piezas (±0.3 pt). Si se recorta a mano sin «sin línea de borde», puede quedar un hueco o un solape en la unión, pero nunca desfasada."),
        ("fixed", "El punto de llegada a un buzón es donde la línea toca la bóveda: una línea que ATRAVIESA una bóveda ya no cuenta como «la que cruza» en la bóveda siguiente donde solo muere. Antes esa confusión ponía el nodo en una esquina de la segunda caja y las llegadas daban un rodeo por el borde hasta él (hoja 3 del DU06). Ahora, sin línea que la atraviese, cada llegada para donde toca el símbolo."),
        ("fixed", "Bóvedas: se acabaron las líneas inventadas alrededor de una bóveda. (1) Una llegada solo va al nodo interior si el nodo queda sobre su eje con un quiebre CORTO (≤ medio lado menor de la bóveda); si tendría que cruzar media caja en diagonal, para en el borde — eso dibujaba un abanico de líneas en la hoja 3 del DU06 que el usuario reportó. (2) El nodo (la CAJA) se mantiene SIEMPRE dentro del recuadro del símbolo: antes podía quedar hasta un hueco del linetype por fuera y las llegadas formaban un triángulo en el papel. (3) Un tramo que muere a más de un hueco del linetype de la bóveda ya no se prolonga hasta ella: entre el último guión y la caja no hay tinta. Auditoría de las 19 hojas: todo segmento de la centerline de más de 6 pt fuera de una bóveda tiene tinta del plano debajo."),
        ("fixed", "Un chaflán ya no se toma por codo: el plano gira a veces con dos guiones RECTOS y el quiebre escondido en el hueco entre ellos. Ahora cada guión bajo el arco tiene que estar CURVADO como pide el radio (sobre un círculo, un guión de cuerda L se aparta de su propia recta r − √(r²−(L/2)²)); la tinta de guiones rectos, de letras y de guiones cortos no sostiene un codo. En el DU06 esto quita el falso codo de la hoja 4 que reportó el usuario y otro de la hoja 15, y deja 15 codos, todos sobre curva dibujada."),
        ("fixed", "Codos reconocidos con la TINTA del plano: el círculo de cada codo se ajusta ahora a los guiones curvos del linetype (los vectores del PDF), no a la centerline ya simplificada, y solo con la tinta de ESA línea (una paralela cercana ya no tuerce el arco) y del trazo curvo (las rectas vecinas tampoco). Un codo solo se crea si la tinta del sector va sobre el arco: un quiebre con una astilla del plot ya no se toma por curva. En el DU06 hoja 4 pasan de 7 a 9 codos, todos sobre el dibujo (error cuadrático ≤0.8 pt) y ninguno aproximado."),
        ("added", "Curvas que MUEREN en un nodo (un ramal que curva y termina sobre otra línea, en una bóveda o en el borde): antes quedaban como polilínea porque no hay una segunda recta. Ahora el arco se cierra con el círculo tangente a la recta que llega y que PASA por ese nodo — recta + nodo + tinta, nada inventado. Y cuando la recta del codo es la línea que cruza en un tee, el vértice se escribe en el punto de tangencia (sobre esa misma línea), para que el tramo recto no quede más corto que la tangente y el arco no se recorte."),
        ("added", "Codos: se toman también las curvas que el plano dibuja «a mano» (polilínea de cuerdas o espiral, no un arco tangente exacto): si un arco tangente a las dos rectas queda a ≤3 pt de la tinta se importa como codo APROXIMADO — en la vista previa va a trazos y el resumen dice cuántos y el desvío máximo. Y un ramal que entra tangente a una línea (tee) cierra su arco en el tee mismo, con la recta de esa línea. La vista previa también cuenta las curvas que quedan como polilínea (curva compuesta de radio variable) para que se vea que no se inventó un arco."),
        ("changed", "Vista previa del reconocimiento: los cuatro botones van en una cuadrícula alineada (Componer hoja… / Ajustar capas… arriba, Cancelar / Continuar e importar abajo; la primaria en color, las demás neutras). Compositor: «Tomar área» y «Continuar» sin icono."),
        ("fixed", "Detección vectorial/escaneo: un plano escaneado y pasado por un vectorizador (miles de trazos «calcados» pero sin texto, fuentes ni capas) ya no se toma por un plot CAD: va directo al dibujo manual y no entra al compositor ni a «Capas de la hoja». Un plot solo cuenta como vectorial si además de trazos tiene texto/fuentes o capas OCG; una imagen a página completa con anotaciones encima sigue siendo escaneo."),
        ("changed", "Compositor: los botones conmutables («Imán a líneas», «Sin línea de borde», «Imán», «Extremos», «Puentes») se ven inequívocamente activos (fondo verde del tema, icono claro). Al tomar un área aparece unos segundos «✔ Área tomada como pieza N» en el panel 2, para cuando el panel de la hoja compuesta está plegado."),
        ("changed", "Menú Ver: se quitan «Organizar hojas…» y «Capas de hojas organizadas…» (flujo antiguo); la hoja compuesta los reemplaza."),
        ("added", "Bóvedas sin línea que las toque (capas de bóvedas existentes VALT/MANH o contorno en la capa de la línea) se importan igual como CAJA suelta con su contorno y medidas — en Civil 3D serán sólidos; se conservan al reconstruir buzones y se exportan al DXF. Las estructuras propuestas (U-PROP…), postes y cajas de paso siguen sin importarse. La vista previa dibuja también el contorno de esas bóvedas sueltas."),
        ("fixed", "Codos: una cadena «curva, recta corta, curva» que no cabe en un solo círculo se resuelve como dos codos (o los que cierren), en vez de perder los dos; una cuerda corta dentro de otra curva ya no sirve de recta tangente, y el arco entero tiene que ir sobre la línea reconocida (≤1.5 pt): donde el plano sigue recto no se inventa curva."),
        ("fixed", "Codos reconocidos, auditoría al milímetro: la esquina y las tangentes salen de las RECTAS de los guiones del plano (no del empalme corto entre el último guión y el trazo curvo, ni del salto sobre una letra «e»), y el círculo es el tangente a esas dos rectas que pasa por el trazo curvo del PDF. En el DU06 (hoja 4) un codo quedaba con la esquina 3.7 pt fuera y la tangente torcida 4.75°; ahora las cuatro tangentes caen sobre los guiones a menos de 0.5 pt y el arco sobre la tinta a menos de 1 pt. Nada se inventa: si el arco no es tangente a sus rectas se queda como polilínea. Se cubren huecos/letra antes del arco, arcos a guiones, giros de 30° a 120° y curvas compuestas (dos radios no se funden en uno)."),
        ("fixed", "El editor dibuja el arco REAL de cada esquina curva (tangente a los dos tramos con el radio en pies, mismos puntos de tangencia que generará el plugin) en vez de un símbolo de codo a escala fija que no caía sobre la curva del plano; los puntos de tangencia se marcan y, si el radio no entra en los tramos (el plugin lo recorta), el arco va a trazos."),
        ("changed", "«Capas de la hoja»: las casillas del panel Utilidades ya no solo filtran la lista — desmarcar una utilidad (Agua, Gas…) apaga todas sus capas en la hoja (y en el reconocimiento) y las quita de la lista; al volver a marcarla cada capa recupera el estado que tenía. «Todas» enciende/apaga el conjunto. El buscador sigue siendo solo un filtro."),
        ("added", "Minimapa en «Capas de la hoja» (esquina inferior izquierda): esquema de cómo está organizada la hoja de trabajo — una caja por hoja tomada, con su número (y su PDF si hay varios) en su posición relativa — y el recuadro de lo que se ve en pantalla. Clic o arrastre en el mapa centra la vista ahí."),
        ("fixed", "Unión recta: tras el imán, un ajuste fino por mínimos cuadrados con todas las parejas de extremos afina la posición a centésimas de punto (las líneas inclinadas fijan también la normal de la costura), y cada puente prolonga la línea por su propia recta hasta el borde de su pieza en vez de ir en diagonal de extremo a extremo (sin quiebre angular)."),
        ("fixed", "Costura milimétrica entre piezas: desaparece la línea finísima que quedaba en la unión (antialiasing del borde: la franja blanca ahora sobresale 0.5 pt hacia afuera), los extremos y puentes se toman en el borde interior de la franja para que cada línea que cruza se complete encima de ella, y el imán une los bordes de las piezas exactamente (borde con borde) alineando de lado solo a lo largo de la costura."),
        ("changed", "Calidad de imagen: en «Área a tomar» y en la hoja compuesta, al hacer zoom se re-renderiza nítida la parte visible (de TODAS las piezas a la vista, con tope de píxeles), en vez de una sola pieza «enfocada»."),
        ("fixed", "El compositor abre maximizado a la primera (antes hacían falta dos clics)."),
        ("added", "Seleccionar una pieza en la hoja compuesta lleva el panel «Área a tomar» a su PDF y hoja con su área marcada: al ajustar el rectángulo la pieza se actualiza sola. «Nueva pieza» vuelve al modo normal."),
        ("changed", "Los extremos para el imán y los puentes solo salen de trazos de línea (≥3 pt, sin letras ni símbolos explotados ni rellenos); un extremo que muere cerca del borde alinea y hace puente pero no pega piezas (evita solapes). Botones de acción solo con icono (Agregar PDF, girar, quitar, ajustar)."),
        ("changed", "«Organizar hojas» deja de ser un paso del asistente (sigue en el menú Ver). El botón «Cambiar de hoja…» del preview ahora es «Componer hoja…» y vuelve al compositor. Menú Ver → «Componer hoja de trabajo…» lo abre en cualquier momento."),
        ("changed", "El proyecto guarda la composición y los PDF de origen completos; al reabrir se puede volver al compositor con todo igual."),
        # ── Bloque: Drenaje en el motor de reconocimiento + auditoría hoja por hoja ──
        ("added", "El motor de reconocimiento (antes solo Eléctrico) reconoce también Drenaje: centerline «C-STRM-UNGD-E/N» y estructuras (catch basins/manholes «V-STRM-…», «C-STRM-CTCH-BASN…», «C-STRM-STRC…»; se excluyen «-WALL»/«-STRC» de la propia centerline, que son geometría auxiliar del conducto). El asistente deja elegir Eléctrico, Drenaje o ambos a la vez; el preview y la importación muestran cada utilidad por separado."),
        ("fixed", "Auditoría hoja por hoja del DU06 en Drenaje: las hojas de PERFIL (estación/elevación, p.ej. «OFFSET MANHOLE PROFILES») no son planta pero reutilizan el mismo nombre de capa que la centerline para dibujar la tubería en corte — antes salían como rutas fabricadas mezclando coordenadas de estación y elevación a escalas distintas (horizontal 1\"=20', vertical 1\"=4'). Ahora se detecta la grilla «C-PROF-GRID-…» (con el mismo recorte que el resto del reconocimiento) y se excluye SOLO esa zona; una hoja mixta (planta + perfiles pequeños, como la hoja 3) conserva su planta intacta."),
        ("fixed", "El linetype de Drenaje trae «sd» (dos letras) donde Eléctrico trae «e» (una); la «d» sale partida en dos trazos del PDF (asta recta + bucle) y esa asta, sin nada que lo evite, se confundía con la barra «/» de utilidad abandonada — salía el aviso «Patrón de marcadores en una capa activa» en casi todas las hojas de planta de Drenaje del DU06. Ahora una letra partida se reconoce porque se REPITE (la misma letra estampada muchas veces a lo largo de la línea, con el mismo largo de asta aunque rote con ella); una marca «/» real que por coincidencia cae junto a una letra (un caso aislado — se vio en el eléctrico de la hoja 9) se sigue detectando igual, y de paso reveló un codo real que esa asta suelta tapaba (hoja 3 eléctrico: 6→7 codos, verificado sobre la tinta)."),
        ("fixed", "Cobertura de guiones en Drenaje: el último guión antes de una bóveda o de una esquina/T podía quedar «sin cubrir» en naranja aunque la ruta sí llegara ahí (el nodo se ajusta al borde de la bóveda o a la intersección exacta de la esquina, unos puntos antes de donde termina el trazo real del PDF) — subía la cobertura reportada de 90-98 % a 100 % en 14 de las 16 hojas de planta del DU06."),
        ("fixed", "«Bóvedas sin línea cercana» ya no cuenta postes ni cajas de paso menores a 2 pies (nunca se iban a importar como bóveda — el filtro ya existía al armar la vista previa, pero el CONTEO del aviso no lo aplicaba): en el DU06 bajó de 8-19 símbolos por hoja a 0-3, y de 69 a 0 en la hoja «KEY MAP» (sin ninguna línea de drenaje)."),
        ("fixed", "Drenaje, hoja 4 del DU06: el lateral «sd» que vive en la capa «C-STRM-UNGD-E-NPLT» no se reconocía (el sufijo «-NPLT» se excluía, pero la línea está impresa en el PDF); ahora entra como centerline de drenaje. «-WALL»/«-STRC» siguen fuera."),
        ("fixed", "Drenaje: un tramo salía DOBLE (MH → caja de captación): un guión corto entre las letras «sd» y la caja, con 1° de deriva respecto del resto de su línea, armaba su propia corrida y se volvía a trazar encima. Ahora un guión que cae entero dentro de otra corrida y sobre su recta es parte de ella."),
        ("fixed", "Drenaje: dos cajas vecinas que no se tocan (a menos de 4 pt) se fundían en una sola bóveda, y una línea que pasaba junto a la más chica moría en su borde sin llegar a su propia caja. Ahora son dos estructuras, y cada extremo de línea va a la caja en la que realmente entra (la que lo contiene o la más cercana), no a la primera de la lista: sin tramos inventados cruzando una caja hasta la siguiente (hoja 11) y sin cortar tinta antes de tiempo (hoja 14)."),
        ("fixed", "Drenaje: una misma línea repetida trazo por trazo en dos xrefs (capas «…GLINE_UG|C-STRM-UNGD-E» y «…EXIST_SD-GLINE|C-STRM-UNGD-E» en la hoja 4) se importaba dos veces, una encima de otra. Ahora se reconoce una sola vez (con aviso), sin perder ningún trazo propio de la repetida. Estas cuatro reglas de drenaje no cambian el reconocimiento eléctrico (verificado vértice por vértice en las 19 hojas del DU06)."),
        ("added", "Componer hoja: las hojas «sin capas» se marcan en la lista (en gris, «Hoja N · sin capas») y al elegirlas aparece un aviso. Son hojas cuyos vectores no están en ninguna capa del PDF (hoja aplanada): apagar capas no las cambia y el reconocimiento por capas no puede encontrar utilidades en ellas (p. ej. DU08 hojas 3–19, DU10 hojas 30–37). El reconocimiento de una hoja así también lo explica en sus avisos."),
        ("fixed", "Eléctrico en planos de otros paquetes (DU08/DU10): las líneas PROPUESTAS «—E—» (continuas, con la letra en mayúscula según la leyenda) vienen en capas «C-ELEC-UGND-…» / «C-ELEC-3MI-UGND-N» (UGND en vez de UNGD, con un segmento de paquete en medio) y no se reconocían; ahora sí, junto con sus estructuras «C-ELEC-3MI-STRC-N». Los muros del ducto «C-ELEC-UNGD-WALL-N» ya no entran como línea. Sin cambios en el DU06."),
        ("fixed", "Abandonadas con pocas marcas: una línea de capa «-A» que lleva sus barras «/» se marca abandonada (AB) aunque la capa entera tenga solo 2 marcas — antes hacían falta 3 para aprender el paso del linetype y la línea salía activa (DU08 hoja 39, curva con 2 «/» a 68 pt, el mismo paso que el DU06). Vale para Eléctrico y Drenaje."),
        ("fixed", "Punta de línea en otro color («fuera de patrón»): en una línea CURVA a guiones, el último trazo —el remate del linetype, más largo que el guión típico— se tomaba por un leader y no se importaba (DU08 hoja 39). Ahora un trazo que sigue de frente el rumbo del guión anterior, a menos de un hueco del patrón, es parte de la línea; un leader de verdad (que nace de costado, desde un texto) sigue descartándose. Vale para Eléctrico y Drenaje; el DU06 no cambia."),
        ("changed", "Aviso específico para las capas «-D» (existente A ABANDONAR según la leyenda, con «//»): antes salían como «patrón de marcadores en una capa ACTIVA»."),
        ("fixed", "Drenaje: la camisa del tubo «C-STRM-UNGD-CASE-N» (rectángulo alrededor de la tubería) ya no se toma como centerline — salía como un par de líneas paralelas."),
        ("fixed", "Componer hoja: la primera vez que dos piezas se juntaban con el imán la ventana se congelaba unos segundos (se leían todos los vectores de la hoja en pleno arrastre, y por separado para cada cálculo). Ahora la lectura se hace una sola vez por hoja y se reutiliza, y la match line de cada pieza se prepara al agregarla: la unión responde al instante."),
    ]),
    ("1.1.9", [
        ("added", "Los tramos reconocidos de la misma capa se unen en rutas por buena continuación: en cada cruce se sigue de frente y el ramal empieza otra ruta. Si no hay trayectoria clara, no se une nada. No se mueven ni se inventan puntos, ni se cruzan capas distintas o activas con abandonadas. En la vista previa, «Unir tramos en rutas» (activada) lo deshace al momento."),
    ]),
    ("1.1.8", [
        ("changed", "Las utilidades eléctricas abandonadas se dibujan del mismo color que la activa. Solo se distinguen por (AB) en la lista; ya no van a trazos ni con otro matiz."),
    ]),
    ("1.1.7", [
        ("fixed", "Un ramal de la misma capa eléctrica (guiones del linetype, aunque uno sea un poco más largo, más el codo) se une a la centerline: nace en la línea principal, quiebra en el codo y el otro extremo queda libre. Ya no se pinta violeta como leader. Un trazo continuo solo, sin contacto con esa red, sigue fuera."),
    ]),
    ("1.1.6", [
        ("fixed", "El reconocimiento reconstruye cada capa OCG de líneas por separado: una capa eléctrica que no es la utilidad (p.ej. U-PROP-ESFV-ELEC-STRUCT) ya no se cose ni se imana con C-ELEC-UNGD-E. Las bóvedas solo cuentan si son un símbolo compacto con caja/círculo; un linetype disfrazado de estructura no atrae extremos. Los ramales de la misma capa que quedaban sin dibujar se cubren si son guiones del patrón."),
    ]),
    ("1.1.5", [
        ("added", "Utilidades eléctricas ABANDONADAS: la capa de estado «-A» (C-ELEC-UNGD-A, linetype «──/── e ──») se reconoce igual que la activa pero se importa marcada como abandonada (AB), como la casilla «Abandonado» del dibujo manual (en el DXF sale con el linetype discontinuo). Las barras «/» del linetype se tratan como marcadores (no quedan «sin cubrir»); el contorno de bóveda que el plot dibuja en esa misma capa se detecta como bóveda (la línea para en su borde y el contorno no se dibuja); activas y abandonadas se reconstruyen por separado (son pipes distintas). En la vista previa van a trazos y la lista de capas las señala «(abandonada)»."),
        ("changed", "Bóvedas: un trazo continuo (sin patrón) que solo nace en el borde y sale hacia afuera ya no se toma como continuación de la línea que llega por el lado opuesto (ambos paran en el borde); sí cuenta si el trazo entra y cruza la bóveda."),
        ("fixed", "Un ramal abandonado que nace sobre su propia línea junto a una bóveda activa ya no se «engancha» a esa bóveda con un tramo inventado: un extremo que muere sobre otra línea es una T con esa línea (nos basamos en las capas)."),
        ("changed", "Precisión de los puntos de quiebre: un extremo que muere sobre otra corrida es una T sobre ella (antes podía formar una esquina fuera de la línea con un tercer extremo cercano); los ticks «┤» de fin de tramo quedan como extremo–T–extremo y sus puntas nunca se unen a otra línea (ni a la que muere a 4 pt de ellas); una esquina nunca se traga más de media corrida; un cruce en X con hueco sigue siendo una sola línea; la línea que atraviesa una bóveda y sigue un trozo corto conserva borde, nodo, borde y su extremo; y las transiciones suaves se simplifican a 1.5 pt (las curvas siguen a 1 pt). Hoja 9 del DU06: 98.4 % → 100 %."),
        ("changed", "Ya no se pide confirmar las capas eléctricas: las capas de líneas y bóvedas se asignan solas por su nombre y la vista previa del reconocimiento las muestra de forma informativa (cabecera con la utilidad y su color, «Capas usadas: Líneas / Bóvedas»). Si el plot usa otros nombres, «Ajustar capas…» permite indicarlas a mano y vuelve a reconocer; si no se encontró ninguna, la vista previa lo avisa y no deja importar."),
        ("added", "«Cambiar de hoja…» en la vista previa del reconocimiento: lista de hojas → capas de la hoja → vista previa de la hoja nueva ya reconocida, sin pasar por el editor."),
    ]),
    ("1.1.4", [
        ("changed", "Paso «Capas de la hoja» reorganizado: las capas se agrupan por utilidad (Agua, Alcantarillado, Drenaje, Gas, Eléctrico, Telefonía y Otras — las mismas del desplegable «Tipo de utilidad», cada una con su color) a partir del nombre de la capa; el panel «Utilidades» filtra la lista (o «Todas») y combina con el buscador."),
        ("added", "Cambio de hoja sin salir del paso de capas (◀ Hoja N / M ▶): la vista previa y los conteos se actualizan y las capas marcadas se conservan. Después, al cambiar de hoja en el editor (◀ ▶ o nº de página) la nueva hoja se reconoce con las mismas capas y roles ya confirmados y se muestra la vista previa para importar."),
    ]),
    ("1.1.3", [
        ("fixed", "Reconocimiento eléctrico: centerlines más continuas y precisas (snap de extremos, colapso de trazos paralelos, cosido colineal por grafo y Douglas–Peucker). Menos cortes artificiales y menos dobles desfasados en el preview."),
    ]),
    ("1.1.2", [
        ("added", "Tras elegir capas, se confirman roles OCG (líneas / bóvedas / ignorar) por si el plot usa otros nombres."),
        ("added", "El reconocimiento eléctrico vuelve a correr: preview con líneas listas (inicio, quiebres, fin) como dibujo manual y bóvedas VALT como puntos; Continuar las importa al editor (pipes ELECTRICO + cajas)."),
    ]),
    ("1.1.1", [
        ("added", "Vista previa de reconocimiento al abrir un PDF bien ploteado: eliges la hoja, se reconocen utilidades eléctricas subterráneas (capas C-ELEC-UNGD) y se muestran dibujadas como el trazo manual. Solo preview — aún no se importan al inventario."),
        ("added", "Reconocimiento eléctrico reconstruido desde cero (núcleo geométrico nuevo): aprende el patrón del linetype del propio plano (guiones, letras «e», huecos), reconstruye cada corrida de inicio a fin con sus quiebres, resuelve esquinas por intersección exacta, T, quiebres suaves, arcos discontinuos y bóvedas como vértices compartidos. Un extremo nunca se mueve fuera de su propia recta, así ninguna línea se inclina. Cobertura medida en el DU06: 97–100 % por hoja (antes 75–89 %)."),
        ("added", "La vista previa muestra control de calidad: porcentaje de cobertura, guiones que ninguna línea cubrió (naranja), trazos continuos fuera de patrón como leaders/flechas (violeta, no se importan) y bóvedas sin línea cercana."),
        ("added", "Al importar, los quiebres sin bóveda (esquinas suaves, arcos) quedan como cajas OCULTAS (Estructura nula en Civil 3D): solo las bóvedas reales salen como CAJA visible. Las pipes reconocidas guardan el tipo de cada vértice en el proyecto."),
        ("fixed", "Las líneas reconocidas ya no superan el marco de la vista de planta: la geometría se recorta por los clips reales del PDF (marco de la vista, XCLIP de referencias) y un extremo creado por el recorte no forma esquinas ni se prolonga. Los codos «⌒» que conectan un conduit con el borde de la bóveda se reconocen como curvas (antes se descartaban como letras)."),
        ("changed", "Bóvedas, ajustes finos: la llegada al nodo interior es un solo tramo recto borde→nodo (sin quiebre intermedio); un stub corto colineal con una línea al otro lado de la bóveda cuenta como continuidad de esa línea; las curvas/continuas que salen de una bóveda nunca se cosen entre sí en sus puntas (conduits cortados por el límite de la vista); los trozos cortos que tocan una bóveda se conservan y se conectan al nodo de llegada más cercano."),
        ("added", "Reglas de bóveda según los apuntes (revisadas): toda línea llega al buzón por su propia recta y SIEMPRE deja un punto de quiebre donde choca con el borde (entrada y salida). Dentro del buzón no se inventa nada a partir del símbolo: si una línea de red lo atraviesa (o dos llegan colineales por lados opuestos), el nodo interior se calcula con las llegadas —sobre la línea que atraviesa, en la intersección si son dos— y las demás llegan a él siguiendo su eje con un quiebre corto. Si ninguna línea lo atraviesa (bóveda grande, stubs, curvas), cada una termina en el borde y ahí queda su caja: el usuario completa a mano. Dos conduits que convergen en ángulo rasante nacen en un vértice compartido sobre la línea principal; las corridas se parten donde los guiones se apartan >0.75 pt para que todo vértice quede sobre la línea de la capa."),
        ("fixed", "Una línea CAD con deriva de 1–2 pt (dibujo casi recto) ya no sale como dos líneas superpuestas terminando en la misma bóveda: cada guión se asigna a la recta que mejor ajusta y las corridas superpuestas se funden. La línea que atraviesa una bóveda se importa como UNA sola polilínea con la bóveda de vértice (antes se partía en dos en el nodo)."),
        ("added", "Paso «Capas de la hoja» antes de la vista previa: lista todas las capas del plano (con su cantidad de trazos) y permite mostrarlas u ocultarlas con casillas, viendo el resultado en vivo. Las capas ocultas no se dibujan en el lienzo ni se usan en el reconocimiento. Incluye buscador y botones Mostrar/Ocultar todas."),
    ]),
    ("1.1.0", [
        ("added", "Nuevo diseñador de Bancoductos (Duct Bank): dibuja la sección con envolvente, márgenes, redondeo de esquinas, reglas de separación y de resguardo al borde. Cada bancoducto se asigna a una utilidad del plano y al importar en Civil 3D se crea el sólido 3D del contenedor + los conductos internos como tuberías reales."),
        ("added", "Panel «Bancoductos» en el inventario derecho: lista todos los bancoductos del proyecto con botones Nuevo / Editar / Duplicar. Doble-click en una fila abre el diseñador ya cargado con ese bancoducto. Click derecho sobre una tubería del plano ofrece «Crear/Editar bancoducto»."),
        ("added", "Opción para elegir si se dibuja el contenedor 3D del bancoducto o solo los conductos internos (útil cuando el contenedor de concreto ya existe en el DWG)."),
        ("added", "Reglas de diseño OBLIGATORIAS: separación mínima entre conductos (2\") y resguardo al borde interior (3\") pre-cargadas por defecto. Si intentas colocar o mover un conducto violando la regla, se bloquea y aparece un banner rojo explicando qué falla."),
        ("added", "Botón «Mostrar medidas»: activa un overlay con las cotas rojas automáticas entre cada conducto y sus vecinos (o al borde del contenedor). Se apaga con Escape o volviendo a hacer click en el botón."),
        ("added", "Silueta fantasma al dibujar conducto: al mover el mouse en modo «Dibujar conducto» aparece el conducto en verde si las reglas permiten colocarlo ahí, o en rojo si no. Un click coloca sólo cuando está verde."),
        ("added", "Rejilla 1\"×1\" dentro del contenedor para orientarte a la escala real mientras diseñas."),
        ("added", "Escape en el diseñador: apaga «Mostrar medidas», o sale de la herramienta activa a Puntero, o deselecciona el conducto. Ya no cierra la ventana por accidente."),
        ("added", "Selector de idioma en Archivo → Opciones… La app se puede alternar entre Español e Inglés; la elección se recuerda al reabrir."),
        ("added", "Diálogo de Opciones en el menú Archivo (pensado para crecer con más preferencias en el futuro)."),
        ("added", "Menú contextual (click derecho) en las tuberías del inventario: crear o editar el bancoducto asignado sin salir del contexto."),
        ("changed", "El botón «Abrir diseñador de Duct Bank» del panel principal siempre abre un diseño en blanco (para editar uno existente usa el panel «Bancoductos»)."),
        ("changed", "La cota invert del bancoducto ahora manda el FONDO del contenedor (parte inferior externa), como en las tuberías normales. Los conductos internos se distribuyen correctamente hacia arriba desde ese fondo."),
        ("changed", "Las cotas por tramo (VertexInv) del pipe padre ahora se aplican también al sólido del contenedor y a los conductos internos — antes solo se usaban en tuberías normales."),
        ("changed", "Zoom del lienzo principal: acercar hasta 4000% y alejar hasta 30% con la rueda o los botones (antes 1000% / 10% y el botón se saltaba el límite)."),
        ("changed", "El botón «+ Nuevo» del panel de bancoductos ahora sí crea uno desde cero (antes cargaba el último diseño)."),
        ("changed", "Rediseño del diseñador de bancoductos: acciones «Cancelar / Guardar y cerrar» debajo del canvas, «Puntero» unificado (click selecciona, arrastra mueve), banner rojo sobre el canvas cuando hay problemas, panel «Identificación» al inicio, panel «Conducto» contextual (cambia entre modo nuevo/editar)."),
        ("changed", "Modo oscuro mejorado: el bancoducto asignado a la tubería seleccionada ya se lee sin problemas, y el título en «Duct Bank: ...» dejó de salir con azul ilegible sobre fondo negro."),
        ("changed", "Los tamaños de tubería que faltan en el catálogo se instalan automáticamente al importar (evita el fallback silencioso a un diámetro distinto)."),
        ("fixed", "El redondeo de esquinas del bancoducto ahora sí se respeta en el sólido 3D de Civil 3D (antes se dibujaba siempre con esquinas rectas aunque en el diseñador se viera redondeado)."),
        ("fixed", "Bancoductos con pendiente (invert distinto entre extremos) o secciones altas (H>W) ya se dibujan como sólido 3D. Antes fallaban en silencio y sólo aparecían los conductos internos."),
        ("fixed", "En curvas del path, el sólido del bancoducto y los conductos internos ahora comparten el mismo centro de curva (concéntricos): los cables ya no se salen del contenedor ni el contenedor de los cables."),
        ("fixed", "La tubería padre del bancoducto ya no se dibuja como cilindro 3D dentro del sólido (aparecía como un conducto fantasma extra en la cara inferior). Se sigue usando para generar los buzones en los extremos."),
        ("fixed", "En vértices con varios conductos, ya no se apilan varios buzones en el mismo punto — sólo uno por vértice."),
        ("fixed", "Los conductos del bancoducto ya no sobresalen del contenedor en el render 3D (Civil 3D dibuja al diámetro exterior; ahora se fuerza pared 0 en las medidas custom que la app inyecta al catálogo)."),
        ("fixed", "Rediseñar el bancoducto de una utilidad ya no crea dos sólidos superpuestos: se sobreescribe por identidad, no por nombre."),
        ("fixed", "El sólido del bancoducto sigue las cotas de la tubería padre (antes quedaba a Z=0 mientras los conductos usaban las cotas correctas)."),
        ("fixed", "Al abrir el diseñador desde una tubería, ahora carga el bancoducto asignado a ESA tubería (antes cargaba el último editado)."),
        ("fixed", "Los conductos de 1\" muestran su medida con letra más grande para que sea legible (antes quedaba invisible por lo pequeño del círculo)."),
    ]),
    ("1.0.1", [
        ("added", "Alineamientos curvos: el eje de la red sigue el mismo arco (mismo radio) que la tubería curva, en vez de cortar la esquina en recta."),
        ("added", "Botón «Agregar tubería curva»: seleccionas dos tuberías y un radio opcional, y crea la curva tangente y redondea también el eje."),
        ("added", "Selector de versión e idioma de Civil 3D en el toolbar; se guarda en el proyecto y se repone solo al reabrirlo."),
        ("added", "Código de sistema de coordenadas (Huso) en la georreferenciación: el dibujo queda seteado con ese sistema al importar la red en Civil 3D."),
        ("added", "Botón «Opacidad» con deslizable para atenuar solo el PDF, y fondo blanco/negro detrás del PDF."),
        ("added", "Georreferenciación: indicador de carga al buscar/descargar el mapa, e imanes a las esquinas redondeadas de las parcelas."),
        ("fixed", "Familias por defecto: ahora se coloca la familia elegida (se emparejan por su GUID, no por el nombre traducido) — antes salía una familia distinta."),
        ("fixed", "Buzones ocultos ya no aparecen como una estructura visible al importar la red."),
        ("fixed", "Redes de presión: los codos salen a la elevación correcta (sobre el eje del tubo)."),
        ("fixed", "Cotas por tramo: ya no se pierden al cerrar y reabrir el proyecto, y la tabla ya no aparece en la pestaña Buzones."),
        ("fixed", "Georreferenciación: el ajuste ya no deforma el plano (transformación de similaridad) y el RMSE es real aunque uses 3 puntos."),
        ("fixed", "Las zonas borradas ya no aparecen en la ventana de georreferenciación."),
        ("changed", "Coordenadas mostradas como X, Y, Z (antes N, E), con 4 decimales; muestran el código de Huso si lo fijaste."),
        ("changed", "Los nombres de familias se muestran en el idioma del Civil 3D seleccionado."),
        ("changed", "«Trazar centerline» va justo después de «Dibujar utilidad»; ejes X/Y de la georreferenciación en morado; ventana de georreferenciación maximizada al abrir."),
        ("changed", "Tema oscuro y accesibilidad; botones de eliminar en rojo; el membrete ya no se separa a una capa aparte."),
        ("removed", "Función «Emparejar centerline dibujado» de la georreferenciación."),
    ]),
    ("1.0.0", [
        ("release", "Primera versión estable: digitalización PDF → DXF, importación a Civil 3D con familias imperiales de gravedad/presión/conduit, gestión de buzones y cajas, y adjunción automática de Property Sets a tuberías vía Excel."),
    ]),
]
